---
title: "ISSS626-GAA"
---

welcome to ISSS608 Visual Analytics and Applications.I am ***xhwang0226***.

This website showcases my hands-on exercises and learning journey through the course. Each exercise explores different visualization techniques using R, Quarto, and various visualization packages.

## Hands-on Exercises

-   [Hands-on Exercise 1: A Layered Grammar of Graphics with ggplot2](Hands-on/Hands-on_Ex01/Hands-on_Ex01.html)
-   [Hands-on Exercise 2: Thematic Mapping and GeoVisualisation with R](Hands-on/Hands-on_Ex02/Hands-on_Ex02.html)
-   [Hands-on Exercise 3: First-order Spatial Point Patterns Analysis Methods](Hands-on/Hands-on_Ex03/Hands-on_Ex03.html)
-   [Hands-on Exercise 4: 2nd Order Spatial Point Patterns Analysis Methods](Hands-on/Hands-on_Ex04/Hands-on_Ex04.html)
-   [Hands-on Exercise 5: Spatio-Temporal Point Patterns Analysis](Hands-on/Hands-on_Ex05/Hands-on_Ex05.html)
-   [Hands-on Exercise 6: Spatial Weights and Applications Analysis](Hands-on/Hands-on_Ex06/Hands-on_Ex06.html)
-   [Hands-on Exercise 7: Global Measures of Spatial Autocorrelation](Hands-on/Hands-on_Ex07/Hands-on_Ex07.html)
-   [Hands-on Exercise 8: Local Measures of Spatial Autocorrelation](Hands-on/Hands-on_Ex08/Hands-on_Ex08.html)

## In-class Exercises

-   [In-class Exercise 4](In-class/In-class_Ex04/In-class_Ex04.html)
This is a Quarto website.

## Take-home Exercises

-   [Take-home Exercise 1](Take-home/Take-home_Ex01/Take-home_Ex01.html)

To learn more about Quarto websites visit <https://quarto.org/docs/websites>.


