<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Wang Xiaohan">
<meta name="dcterms.date" content="2026-09-23">

<title>Take-home Exercise 1: Geospatial Analytics for Public Safety – ISSS626 Geospatial Analytics</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-09786dbf258358d000c2247dc7a04b56.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">ISSS626 Geospatial Analytics</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercises" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Hands-on Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercises">    
        <li>
    <a class="dropdown-item" href="../../Hands-on/Hands-on_Ex01/Hands-on-Ex01.html">
 <span class="dropdown-text">Hands-on Ex01</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on/Hands-on_Ex02/Hands-on_Ex02.html">
 <span class="dropdown-text">Hands-on Ex02</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on/Hands-on_Ex03/Hands-on_Ex03.html">
 <span class="dropdown-text">Hands-on Ex03</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on/Hands-on_Ex04/Hands-on_Ex04.html">
 <span class="dropdown-text">Hands-on Ex04</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on/Hands-on_Ex05/Hands-on_Ex05.html">
 <span class="dropdown-text">Hands-on Ex05</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on/Hands-on_Ex06/Hands-on_Ex06.html">
 <span class="dropdown-text">Hands-on Ex06</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on/Hands-on_Ex07/Hands-on_Ex07.html">
 <span class="dropdown-text">Hands-on Ex07</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on/Hands-on_Ex08/Hands-on_Ex08.html">
 <span class="dropdown-text">Hands-on Ex08</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-exercises" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">In-class Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-in-class-exercises">    
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex04/In-class_Ex04.html">
 <span class="dropdown-text">In-class Ex04</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercises" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Take-home Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercises">    
        <li>
    <a class="dropdown-item" href="../../Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html">
 <span class="dropdown-text">Take-home Ex01</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Take-home_Ex/Take-home_Ex01/Take-home_Ex01_summary.html">
 <span class="dropdown-text">Take-home Ex01: Executive Summary</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">1. Introduction</a>
  <ul class="collapse">
  <li><a href="#research-questions" id="toc-research-questions" class="nav-link" data-scroll-target="#research-questions">1.1 Research questions</a></li>
  </ul></li>
  <li><a href="#getting-started" id="toc-getting-started" class="nav-link" data-scroll-target="#getting-started">2. Getting Started</a></li>
  <li><a href="#the-data" id="toc-the-data" class="nav-link" data-scroll-target="#the-data">3. The Data</a>
  <ul class="collapse">
  <li><a href="#study-area-bangkok-metropolitan-region-bmr" id="toc-study-area-bangkok-metropolitan-region-bmr" class="nav-link" data-scroll-target="#study-area-bangkok-metropolitan-region-bmr">3.1 Study area: Bangkok Metropolitan Region (BMR)</a></li>
  <li><a href="#road-accident-data" id="toc-road-accident-data" class="nav-link" data-scroll-target="#road-accident-data">3.2 Road accident data</a></li>
  <li><a href="#road-network-data" id="toc-road-network-data" class="nav-link" data-scroll-target="#road-network-data">3.3 Road network data</a></li>
  </ul></li>
  <li><a href="#study-design" id="toc-study-design" class="nav-link" data-scroll-target="#study-design">4. Study Design</a>
  <ul class="collapse">
  <li><a href="#point-event-definition" id="toc-point-event-definition" class="nav-link" data-scroll-target="#point-event-definition">4.1 Point event definition</a></li>
  <li><a href="#spatial-and-temporal-study-window" id="toc-spatial-and-temporal-study-window" class="nav-link" data-scroll-target="#spatial-and-temporal-study-window">4.2 Spatial and temporal study window</a></li>
  <li><a href="#methodological-decisions" id="toc-methodological-decisions" class="nav-link" data-scroll-target="#methodological-decisions">4.3 Methodological decisions</a></li>
  <li><a href="#analytical-assumptions" id="toc-analytical-assumptions" class="nav-link" data-scroll-target="#analytical-assumptions">4.4 Analytical assumptions</a></li>
  </ul></li>
  <li><a href="#data-wrangling-and-quality-assessment" id="toc-data-wrangling-and-quality-assessment" class="nav-link" data-scroll-target="#data-wrangling-and-quality-assessment">5. Data Wrangling and Quality Assessment</a>
  <ul class="collapse">
  <li><a href="#temporal-filtering-and-derived-time-fields" id="toc-temporal-filtering-and-derived-time-fields" class="nav-link" data-scroll-target="#temporal-filtering-and-derived-time-fields">5.1 Temporal filtering and derived time fields</a></li>
  <li><a href="#missing-swapped-and-invalid-coordinates" id="toc-missing-swapped-and-invalid-coordinates" class="nav-link" data-scroll-target="#missing-swapped-and-invalid-coordinates">5.2 Missing, swapped and invalid coordinates</a></li>
  <li><a href="#duplicate-records" id="toc-duplicate-records" class="nav-link" data-scroll-target="#duplicate-records">5.3 Duplicate records</a></li>
  <li><a href="#creating-sf-object-and-spatial-filtering" id="toc-creating-sf-object-and-spatial-filtering" class="nav-link" data-scroll-target="#creating-sf-object-and-spatial-filtering">5.4 Creating sf object and spatial filtering</a></li>
  <li><a href="#location-consistency-check" id="toc-location-consistency-check" class="nav-link" data-scroll-target="#location-consistency-check">5.5 Location consistency check</a></li>
  <li><a href="#accidents-by-province" id="toc-accidents-by-province" class="nav-link" data-scroll-target="#accidents-by-province">5.6 Accidents by province</a></li>
  <li><a href="#observation-process" id="toc-observation-process" class="nav-link" data-scroll-target="#observation-process">5.7 Observation process</a></li>
  <li><a href="#mapping-the-geospatial-data" id="toc-mapping-the-geospatial-data" class="nav-link" data-scroll-target="#mapping-the-geospatial-data">5.8 Mapping the geospatial data</a></li>
  <li><a href="#converting-to-spatstat-objects" id="toc-converting-to-spatstat-objects" class="nav-link" data-scroll-target="#converting-to-spatstat-objects">5.9 Converting to spatstat objects</a></li>
  <li><a href="#preparing-events-for-the-network-analysis" id="toc-preparing-events-for-the-network-analysis" class="nav-link" data-scroll-target="#preparing-events-for-the-network-analysis">5.10 Preparing events for the network analysis</a></li>
  </ul></li>
  <li><a href="#first-order-point-patterns-analysis" id="toc-first-order-point-patterns-analysis" class="nav-link" data-scroll-target="#first-order-point-patterns-analysis">6. First-order Point Patterns Analysis</a>
  <ul class="collapse">
  <li><a href="#temporal-variation" id="toc-temporal-variation" class="nav-link" data-scroll-target="#temporal-variation">6.1 Temporal variation</a></li>
  <li><a href="#intensity-by-province" id="toc-intensity-by-province" class="nav-link" data-scroll-target="#intensity-by-province">6.2 Intensity by province</a></li>
  <li><a href="#network-kde-nkde" id="toc-network-kde-nkde" class="nav-link" data-scroll-target="#network-kde-nkde">6.3 Network KDE (NKDE)</a>
  <ul class="collapse">
  <li><a href="#preparing-the-lixels-objects" id="toc-preparing-the-lixels-objects" class="nav-link" data-scroll-target="#preparing-the-lixels-objects">6.3.1 Preparing the lixels objects</a></li>
  <li><a href="#generating-line-centre-points" id="toc-generating-line-centre-points" class="nav-link" data-scroll-target="#generating-line-centre-points">6.3.2 Generating line centre points</a></li>
  <li><a href="#performing-nkde" id="toc-performing-nkde" class="nav-link" data-scroll-target="#performing-nkde">6.3.3 Performing NKDE</a></li>
  <li><a href="#visualising-nkde" id="toc-visualising-nkde" class="nav-link" data-scroll-target="#visualising-nkde">6.3.4 Visualising NKDE</a></li>
  </ul></li>
  <li><a href="#planar-kde-for-comparison" id="toc-planar-kde-for-comparison" class="nav-link" data-scroll-target="#planar-kde-for-comparison">6.4 Planar KDE for comparison</a>
  <ul class="collapse">
  <li><a href="#automatic-bandwidth-selection" id="toc-automatic-bandwidth-selection" class="nav-link" data-scroll-target="#automatic-bandwidth-selection">6.4.1 Automatic bandwidth selection</a></li>
  <li><a href="#bandwidth-sensitivity" id="toc-bandwidth-sensitivity" class="nav-link" data-scroll-target="#bandwidth-sensitivity">6.4.2 Bandwidth sensitivity</a></li>
  <li><a href="#fixed-vs-adaptive-bandwidth" id="toc-fixed-vs-adaptive-bandwidth" class="nav-link" data-scroll-target="#fixed-vs-adaptive-bandwidth">6.4.3 Fixed vs adaptive bandwidth</a></li>
  <li><a href="#mapping-the-selected-planar-kde" id="toc-mapping-the-selected-planar-kde" class="nav-link" data-scroll-target="#mapping-the-selected-planar-kde">6.4.4 Mapping the selected planar KDE</a></li>
  </ul></li>
  <li><a href="#spatio-temporal-kde-by-month" id="toc-spatio-temporal-kde-by-month" class="nav-link" data-scroll-target="#spatio-temporal-kde-by-month">6.5 Spatio-temporal KDE by month</a></li>
  <li><a href="#spatio-temporal-kde-by-day-of-year" id="toc-spatio-temporal-kde-by-day-of-year" class="nav-link" data-scroll-target="#spatio-temporal-kde-by-day-of-year">6.6 Spatio-temporal KDE by day of year</a></li>
  </ul></li>
  <li><a href="#second-order-point-patterns-analysis" id="toc-second-order-point-patterns-analysis" class="nav-link" data-scroll-target="#second-order-point-patterns-analysis">7. Second-order Point Patterns Analysis</a>
  <ul class="collapse">
  <li><a href="#network-k--and-g-function-analysis" id="toc-network-k--and-g-function-analysis" class="nav-link" data-scroll-target="#network-k--and-g-function-analysis">7.1 Network K- and G-function analysis</a></li>
  <li><a href="#planar-tests-against-csr-for-comparison" id="toc-planar-tests-against-csr-for-comparison" class="nav-link" data-scroll-target="#planar-tests-against-csr-for-comparison">7.2 Planar tests against CSR, for comparison</a>
  <ul class="collapse">
  <li><a href="#clark-evans-test" id="toc-clark-evans-test" class="nav-link" data-scroll-target="#clark-evans-test">7.2.1 Clark-Evans test</a></li>
  <li><a href="#g-function" id="toc-g-function" class="nav-link" data-scroll-target="#g-function">7.2.2 G-function</a></li>
  <li><a href="#l-function" id="toc-l-function" class="nav-link" data-scroll-target="#l-function">7.2.3 L-function</a></li>
  </ul></li>
  <li><a href="#spatio-temporal-k-function" id="toc-spatio-temporal-k-function" class="nav-link" data-scroll-target="#spatio-temporal-k-function">7.3 Spatio-temporal K-function</a></li>
  </ul></li>
  <li><a href="#value-added-analysis-sensitivity-of-nkde-to-bandwidth" id="toc-value-added-analysis-sensitivity-of-nkde-to-bandwidth" class="nav-link" data-scroll-target="#value-added-analysis-sensitivity-of-nkde-to-bandwidth">8. Value-added Analysis: Sensitivity of NKDE to Bandwidth</a></li>
  <li><a href="#integrated-findings-and-discussion" id="toc-integrated-findings-and-discussion" class="nav-link" data-scroll-target="#integrated-findings-and-discussion">9. Integrated Findings and Discussion</a></li>
  <li><a href="#public-safety-planning-and-management-implications" id="toc-public-safety-planning-and-management-implications" class="nav-link" data-scroll-target="#public-safety-planning-and-management-implications">10. Public-safety Planning and Management Implications</a>
  <ul class="collapse">
  <li><a href="#supported-directly-by-the-analysis" id="toc-supported-directly-by-the-analysis" class="nav-link" data-scroll-target="#supported-directly-by-the-analysis">Supported directly by the analysis</a></li>
  <li><a href="#requiring-additional-information" id="toc-requiring-additional-information" class="nav-link" data-scroll-target="#requiring-additional-information">Requiring additional information</a></li>
  </ul></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations">11. Limitations</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">12. References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Take-home Exercise 1: Geospatial Analytics for Public Safety</h1>
<p class="subtitle lead">Network-constrained and Spatio-temporal Point Patterns of Road Traffic Accidents in the Bangkok Metropolitan Region, 2022</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Wang Xiaohan </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 23, 2026</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">September 27, 2026</p>
    </div>
  </div>
    
  </div>
  


</header>


<p><a href="../../Take-home_Ex/Take-home_Ex01/Take-home_Ex01_summary.html" class="btn btn-light btn-lg">View the Executive Summary (slides) →</a></p>
<section id="introduction" class="level1">
<h1>1. Introduction</h1>
<p>Road traffic crashes are a major public-safety problem in Thailand. WHO estimates about 18,218 road deaths in 2021, a rate of 25.4 per 100,000 population and one of the highest in Asia, with motorcyclists accounting for most deaths. The Bangkok Metropolitan Region (BMR), comprising Bangkok and five vicinity provinces, is the country’s largest urban area, where crash patterns are likely to vary strongly across space and time. However, a concentration of crashes does not necessarily mean higher risk, as it may also reflect traffic volume, road density or how crashes are recorded.</p>
<p>Road accidents can only happen on roads, so this study treats them as events on a road network. Following the Network Constrained Spatial Point Patterns Analysis (NetSPAA) approach, the main analysis uses network kernel density estimation (NKDE) for first-order properties and network K- and G-functions for second-order properties. Planar and spatio-temporal methods from earlier exercises are used to describe temporal variation and to compare planar and network results.</p>
<section id="research-questions" class="level2">
<h2 class="anchored" data-anchor-id="research-questions">1.1 Research questions</h2>
<ol type="1">
<li>Where and when are road traffic accidents in BMR concentrated in 2022? (first-order)</li>
<li>Are accidents clustered, regular or approximately random along the road network, compared with complete spatial randomness on the network? (second-order)</li>
<li>Do conclusions change between planar and network-constrained views, and between bandwidths? (comparison and value-added)</li>
</ol>
</section>
</section>
<section id="getting-started" class="level1">
<h1>2. Getting Started</h1>
<p>The four packages used in the network-constrained analysis are loaded first, followed by the packages used for planar and spatio-temporal analysis. A fixed random seed makes all Monte Carlo simulations reproducible.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(sf, spNetwork, tmap, tidyverse,</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>               spatstat, sparr, stpp, terra)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Package</th>
<th>Purpose</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>sf</td>
<td>import, wrangle and transform geospatial data</td>
</tr>
<tr class="even">
<td>spNetwork</td>
<td>lixels, network KDE, network K- and G-functions</td>
</tr>
<tr class="odd">
<td>tmap</td>
<td>thematic mapping</td>
</tr>
<tr class="even">
<td>tidyverse</td>
<td>data wrangling, dates (<code>month()</code>, <code>yday()</code>) and statistical graphics</td>
</tr>
<tr class="odd">
<td>spatstat</td>
<td>ppp/owin objects, planar KDE, Clark-Evans test, G/L functions, envelopes</td>
</tr>
<tr class="even">
<td>sparr</td>
<td>spatio-temporal KDE</td>
</tr>
<tr class="odd">
<td>stpp</td>
<td>spatio-temporal K-function</td>
</tr>
<tr class="even">
<td>terra</td>
<td>convert planar KDE output to a raster for tmap</td>
</tr>
</tbody>
</table>
</section>
<section id="the-data" class="level1">
<h1>3. The Data</h1>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Dataset</th>
<th>Source</th>
<th>Format</th>
<th>Accessed</th>
<th>Coverage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Thailand Road Accident [2019-2022]</td>
<td>Kaggle (Thaweewat R.)</td>
<td>CSV</td>
<td>2026-09-23</td>
<td>Thailand, 2019-2022 (2022 used)</td>
</tr>
<tr class="even">
<td>Thailand ADM1 boundaries</td>
<td>geoBoundaries</td>
<td>Shapefile</td>
<td>2026-09-23</td>
<td>Thailand provinces</td>
</tr>
<tr class="odd">
<td>OpenStreetMap roads</td>
<td>Geofabrik (extract 2026-09-21)</td>
<td>Shapefile</td>
<td>2026-09-22</td>
<td>Thailand</td>
</tr>
</tbody>
</table>
<section id="study-area-bangkok-metropolitan-region-bmr" class="level2">
<h2 class="anchored" data-anchor-id="study-area-bangkok-metropolitan-region-bmr">3.1 Study area: Bangkok Metropolitan Region (BMR)</h2>
<p>BMR is operationalised as Bangkok plus its five vicinity provinces, taken from the full-resolution geoBoundaries ADM1 layer (not the simplified version, to avoid wrongly dropping accidents near provincial borders and the coastline). The province names are checked first, because five of the six end with ” Province”.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(<span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"data/geospatial"</span>,</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">layer =</span> <span class="st">"geoBoundaries-THA-ADM1"</span>,</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">quiet =</span> <span class="cn">TRUE</span>)<span class="sc">$</span>shapeName)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
           Amnat Charoen Province                Ang Thong Province 
                                1                                 1 
                          Bangkok                Bueng Kan Province 
                                1                                 1 
                Buri Ram Province             Chachoengsao Province 
                                1                                 1 
                Chai Nat Province               Chaiyaphum Province 
                                1                                 1 
             Chanthaburi Province               Chiang Mai Province 
                                1                                 1 
              Chiang Rai Province                Chon Buri Province 
                                1                                 1 
                Chumphon Province                           Kalasin 
                                1                                 1 
          Kamphaeng Phet Province             Kanchanaburi Province 
                                1                                 1 
               Khon Kaen Province                    Krabi Province 
                                1                                 1 
                 Lampang Province                  Lamphun Province 
                                1                                 1 
                    Loei Province                  Lopburi Province 
                                1                                 1 
            Mae Hong Son Province            Maha Sarakham Province 
                                1                                 1 
                Mukdahan Province             Nakhon Nayok Province 
                                1                                 1 
           Nakhon Pathom Province            Nakhon Phanom Province 
                                1                                 1 
       Nakhon Ratchasima Province             Nakhon Sawan Province 
                                1                                 1 
     Nakhon Si Thammarat Province                      Nan Province 
                                1                                 1 
              Narathiwat Province         Nong Bua Lam Phu Province 
                                1                                 1 
               Nong Khai Province               Nonthaburi Province 
                                1                                 1 
            Pathum Thani Province                  Pattani Province 
                                1                                 1 
                Phangnga Province              Phatthalung Province 
                                1                                 1 
                  Phayao Province               Phetchabun Province 
                                1                                 1 
             Phetchaburi Province                  Phichit Province 
                                1                                 1 
             Phitsanulok Province Phra Nakhon Si Ayutthaya Province 
                                1                                 1 
                   Phrae Province                   Phuket Province 
                                1                                 1 
            Prachin Buri Province      Prachuap Khiri Khan Province 
                                1                                 1 
                  Ranong Province               Ratchaburi Province 
                                1                                 1 
                  Rayong Province                   Roi Et Province 
                                1                                 1 
                 Sa Kaeo Province             Sakon Nakhon Province 
                                1                                 1 
            Samut Prakan Province             Samut Sakhon Province 
                                1                                 1 
         Samut Songkhram Province                 Saraburi Province 
                                1                                 1 
                   Satun Province                Si Sa Ket Province 
                                1                                 1 
               Sing Buri Province                 Songkhla Province 
                                1                                 1 
               Sukhothai Province              Suphan Buri Province 
                                1                                 1 
             Surat Thani Province                    Surin Province 
                                1                                 1 
                     Tak Province                    Trang Province 
                                1                                 1 
                    Trat Province         Ubon Ratchathani Province 
                                1                                 1 
              Udon Thani Province              Uthai Thani Province 
                                1                                 1 
               Uttaradit Province                     Yala Province 
                                1                                 1 
                Yasothon Province 
                                1 </code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>bmr_names <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Bangkok"</span>, <span class="st">"Nonthaburi Province"</span>, <span class="st">"Nakhon Pathom Province"</span>,</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>               <span class="st">"Pathum Thani Province"</span>, <span class="st">"Samut Prakan Province"</span>,</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>               <span class="st">"Samut Sakhon Province"</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>bmr_sf <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"data/geospatial"</span>,</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>                  <span class="at">layer =</span> <span class="st">"geoBoundaries-THA-ADM1"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(shapeName <span class="sc">%in%</span> bmr_names) <span class="sc">%&gt;%</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">32647</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `geoBoundaries-THA-ADM1' from data source 
  `/Users/wangxiaohan/ISSS626-GAA/Take-home_Ex/Take-home_Ex01/data/geospatial' 
  using driver `ESRI Shapefile'
Simple feature collection with 77 features and 5 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 97.34381 ymin: 5.612851 xmax: 105.6368 ymax: 20.46483
Geodetic CRS:  WGS 84</code></pre>
</div>
</div>
<p>The output should show 6 provinces in WGS 84 / UTM zone 47N (EPSG:32647). <code>st_is_valid()</code> checks that no polygon geometry is invalid.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(bmr_sf)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(bmr_sf)<span class="sc">$</span>epsg</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 32647</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">any</span>(<span class="sc">!</span><span class="fu">st_is_valid</span>(bmr_sf))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>bmr_union <span class="ot">&lt;-</span> <span class="fu">st_union</span>(bmr_sf)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="road-accident-data" class="level2">
<h2 class="anchored" data-anchor-id="road-accident-data">3.2 Road accident data</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>acc_raw <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/aspatial/thai_road_accident_2019_2022.csv"</span>,</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(acc_raw)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 81,735
Columns: 18
$ acc_code                    &lt;dbl&gt; 571905, 3790870, 599075, 571924, 599523, 5…
$ incident_datetime           &lt;dttm&gt; 2019-01-01 00:00:00, 2019-01-01 00:03:00,…
$ report_datetime             &lt;dttm&gt; 2019-01-02 06:11:00, 2020-02-20 13:48:00,…
$ province_th                 &lt;chr&gt; "ลพบุรี", "อุบลราชธานี", "ประจวบคีรีขันธ์", "เชียงใ…
$ province_en                 &lt;chr&gt; "Loburi", "Ubon Ratchathani", "Prachuap Kh…
$ agency                      &lt;chr&gt; "department of rural roads", "department o…
$ route                       &lt;chr&gt; "แยกทางหลวงหมายเลข 21 (กม.ที่ 31+000) - บ้านวั…
$ vehicle_type                &lt;chr&gt; "motorcycle", "private/passenger car", "mo…
$ presumed_cause              &lt;chr&gt; "driving under the influence of alcohol", …
$ accident_type               &lt;chr&gt; "other", "rollover/fallen on straight road…
$ number_of_vehicles_involved &lt;dbl&gt; 1, 1, 2, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, …
$ number_of_fatalities        &lt;dbl&gt; 0, 0, 1, 0, 0, 0, 0, 1, 3, 0, 0, 1, 0, 0, …
$ number_of_injuries          &lt;dbl&gt; 2, 2, 0, 1, 0, 2, 2, 0, 0, 1, 1, 0, 1, 1, …
$ weather_condition           &lt;chr&gt; "clear", "clear", "clear", "clear", "clear…
$ latitude                    &lt;dbl&gt; 14.959105, 15.210738, 12.374259, 18.601721…
$ longitude                   &lt;dbl&gt; 100.87346, 104.86269, 99.90795, 98.80420, …
$ road_description            &lt;chr&gt; "straight road", "straight road", "wide cu…
$ slope_description           &lt;chr&gt; "no slope", "no slope", "slope area", "no …</code></pre>
</div>
</div>
<p><code>incident_datetime</code> is already parsed as a date-time (<code>&lt;dttm&gt;</code>), and <code>latitude</code> and <code>longitude</code> are numeric.</p>
</section>
<section id="road-network-data" class="level2">
<h2 class="anchored" data-anchor-id="road-network-data">3.3 Road network data</h2>
<p>Following the NetSPAA workflow, the road network is imported as a line feature layer. Only roads intersecting BMR are read, because the full Thailand layer is over 600 MB; the spatial filter is converted to EPSG:4326 to match the OSM file. Only major road classes are kept, because all accidents in the dataset are recorded by national road agencies (Section 5.7), which manage these roads.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>bmr_wkt <span class="ot">&lt;-</span> bmr_union <span class="sc">%&gt;%</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">4326</span>) <span class="sc">%&gt;%</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_as_text</span>()</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>major_roads <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"motorway"</span>, <span class="st">"motorway_link"</span>, <span class="st">"trunk"</span>, <span class="st">"trunk_link"</span>,</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"primary"</span>, <span class="st">"primary_link"</span>, <span class="st">"secondary"</span>, <span class="st">"secondary_link"</span>,</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"tertiary"</span>, <span class="st">"tertiary_link"</span>)</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>network <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"data/geospatial"</span>,</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>                   <span class="at">layer =</span> <span class="st">"gis_osm_roads_free_1"</span>,</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>                   <span class="at">wkt_filter =</span> bmr_wkt) <span class="sc">%&gt;%</span></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(fclass <span class="sc">%in%</span> major_roads) <span class="sc">%&gt;%</span></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(osm_id, fclass, name) <span class="sc">%&gt;%</span></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">32647</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `gis_osm_roads_free_1' from data source 
  `/Users/wangxiaohan/ISSS626-GAA/Take-home_Ex/Take-home_Ex01/data/geospatial' 
  using driver `ESRI Shapefile'
Simple feature collection with 621938 features and 10 fields
Geometry type: LINESTRING
Dimension:     XY
Bounding box:  xmin: 99.76608 ymin: 13.43053 xmax: 101.0062 ymax: 14.32775
Geodetic CRS:  WGS 84</code></pre>
</div>
</div>
<p>spNetwork expects both layers to carry complete CRS information, so the CRS and the road classes kept are checked.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(network)<span class="sc">$</span>epsg</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 32647</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(network<span class="sc">$</span>fclass)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
      motorway  motorway_link        primary   primary_link      secondary 
          1268           1720           6273           2452           7339 
secondary_link       tertiary  tertiary_link          trunk     trunk_link 
          2073           5725            425           1464            668 </code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dir.create</span>(<span class="st">"data/rds"</span>, <span class="at">recursive =</span> <span class="cn">TRUE</span>, <span class="at">showWarnings =</span> <span class="cn">FALSE</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(network, <span class="st">"data/rds/network.rds"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
</section>
<section id="study-design" class="level1">
<h1>4. Study Design</h1>
<section id="point-event-definition" class="level2">
<h2 class="anchored" data-anchor-id="point-event-definition">4.1 Point event definition</h2>
<p>A point event is one recorded road traffic accident (one unique <code>acc_code</code>) that occurred between 1 January and 31 December 2022, located by its reported longitude and latitude, and falling inside BMR. For the network analysis, events must also lie within 100 m of a major road, and are snapped to the network by spNetwork. Events are treated as an unmarked point pattern: attributes such as fatalities or vehicle type are not used as weights.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Issue</th>
<th>Handling</th>
<th>Section</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Duplicate records</td>
<td>Removed by unique <code>acc_code</code></td>
<td>5.3</td>
</tr>
<tr class="even">
<td>Repeated locations</td>
<td>Kept, counted with <code>duplicated()</code> and discussed</td>
<td>5.9</td>
</tr>
<tr class="odd">
<td>Missing coordinates</td>
<td>Removed</td>
<td>5.2</td>
</tr>
<tr class="even">
<td>Swapped lat/long</td>
<td>Checked and corrected</td>
<td>5.2</td>
</tr>
<tr class="odd">
<td>Coordinates outside Thailand</td>
<td>Removed</td>
<td>5.2</td>
</tr>
<tr class="even">
<td>Outside BMR</td>
<td>Removed with <code>st_intersects()</code></td>
<td>5.4</td>
</tr>
<tr class="odd">
<td>Outside 2022</td>
<td>Removed</td>
<td>5.1</td>
</tr>
<tr class="even">
<td>More than 100 m from a major road</td>
<td>Excluded from the network analysis</td>
<td>5.10</td>
</tr>
</tbody>
</table>
</section>
<section id="spatial-and-temporal-study-window" class="level2">
<h2 class="anchored" data-anchor-id="spatial-and-temporal-study-window">4.2 Spatial and temporal study window</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Item</th>
<th>Decision</th>
<th>Justification</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Spatial window</td>
<td>Union of 6 BMR provinces (planar); major road network within BMR (network)</td>
<td>Operationalises “Bangkok Greater Metropolitan Area” with official provincial boundaries; the network is the space where accidents can occur</td>
</tr>
<tr class="even">
<td>Temporal window</td>
<td>1 Jan - 31 Dec 2022</td>
<td>Required by the brief for the 2019-2022 dataset</td>
</tr>
<tr class="odd">
<td>Temporal unit</td>
<td>Month (STKDE, 6.5); day of year (STKDE, 6.6; space-time K-function, 7.3; daily graphic, 6.1)</td>
<td>Months give enough events per slice; day of year allows data-driven temporal bandwidths and shows holiday peaks</td>
</tr>
</tbody>
</table>
</section>
<section id="methodological-decisions" class="level2">
<h2 class="anchored" data-anchor-id="methodological-decisions">4.3 Methodological decisions</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Decision</th>
<th>Choice</th>
<th>Justification</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>CRS</td>
<td>WGS 84 / UTM 47N (EPSG:32647)</td>
<td>Metric units for bandwidth and distance; zone 47N covers Bangkok</td>
</tr>
<tr class="even">
<td>Network</td>
<td>OSM major roads (motorway to tertiary, with links)</td>
<td>Matches the agencies that recorded the accidents</td>
</tr>
<tr class="odd">
<td>Lixels</td>
<td>500 m, minimum 250 m</td>
<td>About half the NKDE bandwidth, giving detail without too many lixels</td>
</tr>
<tr class="even">
<td>NKDE</td>
<td>Quartic kernel, simple method, bandwidth 1 km (sensitivity: 0.5 and 2 km)</td>
<td>Quartic and simple follow the NetSPAA workflow; 1 km covers junction-to-corridor scale</td>
</tr>
<tr class="odd">
<td>Network K/G-functions</td>
<td>0-5 km, step 100 m, width 200 m, 50 simulations, Bangkok only</td>
<td>Range covers local to corridor scale; Bangkok only for computation time</td>
</tr>
<tr class="even">
<td>Planar KDE</td>
<td>Gaussian kernel; bw.diggle, bw.ppl, bw.scott, fixed 0.5-5 km, adaptive compared</td>
<td>Used for comparison with the network view</td>
</tr>
<tr class="odd">
<td>Planar edge correction</td>
<td>Border (default for large patterns)</td>
<td>Fast for thousands of points</td>
</tr>
<tr class="even">
<td>Planar simulations</td>
<td>99</td>
<td>Global envelopes with rank 1 give α = 0.01</td>
</tr>
<tr class="odd">
<td>Null models</td>
<td>CSR on the network (binomial process on the network); planar CSR for comparison</td>
<td>Network CSR accounts for the fact that accidents can only occur on roads</td>
</tr>
</tbody>
</table>
</section>
<section id="analytical-assumptions" class="level2">
<h2 class="anchored" data-anchor-id="analytical-assumptions">4.4 Analytical assumptions</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Method</th>
<th>Key assumption</th>
<th>Reasonable here?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>NKDE</td>
<td>Accidents occur on the network, and network distance is the relevant distance</td>
<td>Yes for accidents within 100 m of a major road; not for accidents on minor roads, which are excluded</td>
</tr>
<tr class="even">
<td>Network K/G vs network CSR</td>
<td>Accidents are equally likely anywhere on the network</td>
<td>Partly: traffic volume varies strongly between roads, so clustering may reflect exposure rather than interaction</td>
</tr>
<tr class="odd">
<td>Planar KDE</td>
<td>Accidents can occur anywhere in the window</td>
<td>No: planar KDE spreads intensity into areas without roads</td>
</tr>
<tr class="even">
<td>Planar G/L vs CSR</td>
<td>Constant intensity across BMR</td>
<td>No: intensity clearly varies, so clustering under planar CSR may just reflect uneven intensity</td>
</tr>
<tr class="odd">
<td>STKDE</td>
<td>Spatial pattern changes smoothly over time</td>
<td>Reasonable for seasonal change, but short holiday peaks are smoothed out</td>
</tr>
<tr class="even">
<td>Space-time K-function</td>
<td>Constant intensity in space and time</td>
<td>No: like planar CSR, it cannot separate interaction from uneven intensity</td>
</tr>
<tr class="odd">
<td>All methods</td>
<td>Recorded accidents represent all accidents</td>
<td>No: data come from national road agencies, so city streets are likely under-recorded</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="data-wrangling-and-quality-assessment" class="level1">
<h1>5. Data Wrangling and Quality Assessment</h1>
<section id="temporal-filtering-and-derived-time-fields" class="level2">
<h2 class="anchored" data-anchor-id="temporal-filtering-and-derived-time-fields">5.1 Temporal filtering and derived time fields</h2>
<p>Records are kept if they occurred in 2022. The boundaries are written as seconds since 1 January 1970 (UTC), because <code>incident_datetime</code> is stored in UTC: 1640995200 is 2022-01-01 00:00 and 1672531200 is 2023-01-01 00:00.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(acc_raw<span class="sc">$</span>incident_datetime))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>acc_2022 <span class="ot">&lt;-</span> acc_raw <span class="sc">%&gt;%</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">as.numeric</span>(incident_datetime) <span class="sc">&gt;=</span> <span class="dv">1640995200</span>,</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>         <span class="fu">as.numeric</span>(incident_datetime) <span class="sc">&lt;</span> <span class="dv">1672531200</span>) <span class="sc">%&gt;%</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">DayofYear =</span> <span class="fu">yday</span>(incident_datetime)) <span class="sc">%&gt;%</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Month_num =</span> <span class="fu">month</span>(incident_datetime)) <span class="sc">%&gt;%</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Month_fac =</span> <span class="fu">month</span>(incident_datetime,</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>                           <span class="at">label =</span> <span class="cn">TRUE</span>,</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>                           <span class="at">abbr =</span> <span class="cn">FALSE</span>))</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(acc_2022)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 21032</code></pre>
</div>
</div>
</section>
<section id="missing-swapped-and-invalid-coordinates" class="level2">
<h2 class="anchored" data-anchor-id="missing-swapped-and-invalid-coordinates">5.2 Missing, swapped and invalid coordinates</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(acc_2022<span class="sc">$</span>latitude) <span class="sc">|</span> <span class="fu">is.na</span>(acc_2022<span class="sc">$</span>longitude))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 189</code></pre>
</div>
</div>
<p>Records whose latitude and longitude appear to be swapped (latitude in Thailand’s longitude range and vice versa) are corrected rather than dropped.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>acc_fixed <span class="ot">&lt;-</span> acc_2022 <span class="sc">%&gt;%</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">swapped =</span> latitude <span class="sc">&gt;=</span> <span class="dv">97</span> <span class="sc">&amp;</span> latitude <span class="sc">&lt;=</span> <span class="dv">106</span> <span class="sc">&amp;</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>                   longitude <span class="sc">&gt;=</span> <span class="dv">5</span> <span class="sc">&amp;</span> longitude <span class="sc">&lt;=</span> <span class="dv">21</span>) <span class="sc">%&gt;%</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">latitude_fix =</span> <span class="fu">ifelse</span>(swapped, longitude, latitude),</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">longitude_fix =</span> <span class="fu">ifelse</span>(swapped, latitude, longitude))</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(acc_fixed<span class="sc">$</span>swapped, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>acc_valid <span class="ot">&lt;-</span> acc_fixed <span class="sc">%&gt;%</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(latitude_fix), <span class="sc">!</span><span class="fu">is.na</span>(longitude_fix)) <span class="sc">%&gt;%</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(longitude_fix <span class="sc">&gt;=</span> <span class="dv">97</span>, longitude_fix <span class="sc">&lt;=</span> <span class="dv">106</span>,</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>         latitude_fix <span class="sc">&gt;=</span> <span class="dv">5</span>, latitude_fix <span class="sc">&lt;=</span> <span class="dv">21</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="duplicate-records" class="level2">
<h2 class="anchored" data-anchor-id="duplicate-records">5.3 Duplicate records</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">duplicated</span>(acc_valid<span class="sc">$</span>acc_code))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>acc_dedup <span class="ot">&lt;-</span> acc_valid <span class="sc">%&gt;%</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">duplicated</span>(acc_code))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="creating-sf-object-and-spatial-filtering" class="level2">
<h2 class="anchored" data-anchor-id="creating-sf-object-and-spatial-filtering">5.4 Creating sf object and spatial filtering</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>acc_sf <span class="ot">&lt;-</span> acc_dedup <span class="sc">%&gt;%</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_as_sf</span>(<span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"longitude_fix"</span>, <span class="st">"latitude_fix"</span>),</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">crs =</span> <span class="dv">4326</span>) <span class="sc">%&gt;%</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">32647</span>)</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>acc_bmr_sf <span class="ot">&lt;-</span> acc_sf <span class="sc">%&gt;%</span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">lengths</span>(<span class="fu">st_intersects</span>(acc_sf, bmr_union)) <span class="sc">&gt;</span> <span class="dv">0</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="location-consistency-check" class="level2">
<h2 class="anchored" data-anchor-id="location-consistency-check">5.5 Location consistency check</h2>
<p>Each point is joined to the province it falls in and compared with the province recorded in the data. <code>distinct()</code> removes duplicate rows created by points lying exactly on a provincial border.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">step =</span> <span class="fu">c</span>(<span class="st">"Raw (2019-2022)"</span>, <span class="st">"Year 2022"</span>, <span class="st">"Valid coordinates"</span>,</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>           <span class="st">"After de-duplication"</span>, <span class="st">"Inside BMR"</span>),</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">n =</span> <span class="fu">c</span>(<span class="fu">nrow</span>(acc_raw), <span class="fu">nrow</span>(acc_2022), <span class="fu">nrow</span>(acc_valid),</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>        <span class="fu">nrow</span>(acc_dedup), <span class="fu">nrow</span>(acc_bmr_sf))</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  step     n
1      Raw (2019-2022) 81735
2            Year 2022 21032
3    Valid coordinates 20843
4 After de-duplication 20843
5           Inside BMR  3599</code></pre>
</div>
</div>
<p>Of the 81,735 records, 21,032 occurred in 2022. All dates were parsed successfully. 189 records lacked coordinates and were removed; no swapped or out-of-Thailand coordinates and no duplicate <code>acc_code</code> values were found. 3,599 accidents fall inside BMR.</p>
</section>
<section id="accidents-by-province" class="level2">
<h2 class="anchored" data-anchor-id="accidents-by-province">5.6 Accidents by province</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(acc_bmr_sf<span class="sc">$</span>province_en)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
                 Bangkok             Kanchanaburi            Nakhon Pathom 
                    1801                        4                      134 
              Nonthaburi             Pathum Thani Phra Nakhon Si Ayutthaya 
                     175                      486                        4 
            Samut Prakan             Samut Sakhon                  unknown 
                     669                      324                        2 </code></pre>
</div>
</div>
</section>
<section id="observation-process" class="level2">
<h2 class="anchored" data-anchor-id="observation-process">5.7 Observation process</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(acc_bmr_sf<span class="sc">$</span>agency)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
          department of highways        department of rural roads 
                            2883                              246 
expressway authority of thailand 
                             470 </code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Interpretation">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Interpretation
</div>
</div>
<div class="callout-body-container callout-body">
<p>All 3,599 BMR accidents were reported by national road agencies: the Department of Highways (80.1%), the Expressway Authority of Thailand (13.1%) and the Department of Rural Roads (6.8%). None come from the Bangkok Metropolitan Administration, which manages most local streets in Bangkok. Accidents on these streets are therefore likely under-represented, and concentrations in the following analysis should be read as patterns of recorded accidents on highways, expressways and rural roads, not of all accidents in BMR.</p>
</div>
</div>
</section>
<section id="mapping-the-geospatial-data" class="level2">
<h2 class="anchored" data-anchor-id="mapping-the-geospatial-data">5.8 Mapping the geospatial data</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(bmr_sf) <span class="sc">+</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="at">fill =</span> <span class="st">"grey95"</span>) <span class="sc">+</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_text</span>(<span class="st">"shapeName"</span>, <span class="at">size =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(acc_bmr_sf) <span class="sc">+</span></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_dots</span>(<span class="at">size =</span> <span class="fl">0.1</span>, <span class="at">fill =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_title</span>(<span class="st">"Road accidents in BMR, 2022"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Interpretation">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Interpretation
</div>
</div>
<div class="callout-body-container callout-body">
<p>The 3,599 recorded accidents are not spread evenly across BMR but align along linear corridors radiating from Bangkok towards Pathum Thani, Samut Prakan and Samut Sakhon, with sparser points in Nakhon Pathom. Inner Bangkok shows relatively few accidents despite its density, consistent with the absence of BMA-managed streets from the data (Section 5.7). This visual concentration does not yet indicate clustering or higher risk: it must be assessed against a reference model (Section 7), and the linear pattern suggests that the road network itself shapes where accidents can occur.</p>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(bmr_sf) <span class="sc">+</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="at">fill =</span> <span class="st">"grey95"</span>) <span class="sc">+</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(acc_bmr_sf) <span class="sc">+</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_dots</span>(<span class="at">size =</span> <span class="fl">0.1</span>, <span class="at">fill =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_facets</span>(<span class="at">by =</span> <span class="st">"Month_fac"</span>,</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>          <span class="at">free.coords =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Interpretation">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Interpretation
</div>
</div>
<div class="callout-body-container callout-body">
<p>Faceting by month shows that accidents occur along the same major corridors throughout 2022, suggesting that the spatial structure of recorded accidents is largely stable over time rather than shifting between areas. Differences in the number of points between months are difficult to judge visually from dot maps; monthly counts (Section 6.1) and spatio-temporal KDE (Sections 6.5 and 6.6) are used to assess temporal variation in intensity more rigorously.</p>
</div>
</div>
</section>
<section id="converting-to-spatstat-objects" class="level2">
<h2 class="anchored" data-anchor-id="converting-to-spatstat-objects">5.9 Converting to spatstat objects</h2>
<p>For the planar and spatio-temporal methods, the accidents are converted to a ppp object and combined with an owin object of BMR. <code>st_geometry()</code> keeps only the point locations, so the ppp object carries no marks.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>acc_ppp <span class="ot">&lt;-</span> <span class="fu">as.ppp</span>(<span class="fu">st_geometry</span>(acc_bmr_sf))</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(acc_ppp)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Planar point pattern:  3599 points
Average intensity 3.326903e-07 points per square unit

*Pattern contains duplicated points*

Coordinates are given to 10 decimal places

Window: rectangle = [587647.2, 709360] x [1487640.2, 1576520.5] units
                    (121700 x 88880 units)
Window area = 10817900000 square units</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">any</span>(<span class="fu">duplicated</span>(acc_ppp))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">duplicated</span>(acc_ppp))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 321</code></pre>
</div>
</div>
<p>Some accidents share their exact location with another accident. These may be repeated accidents at the same site, or locations recorded at fixed reference points such as kilometre markers. They are kept, because removing them would discard real accidents; the effect on the planar G-function is discussed in Section 7.2.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>bmr_owin <span class="ot">&lt;-</span> <span class="fu">as.owin</span>(bmr_union)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(bmr_owin)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>accBMR_ppp <span class="ot">&lt;-</span> acc_ppp[bmr_owin]</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>accBMR_ppp.km <span class="ot">&lt;-</span> <span class="fu">rescale.ppp</span>(accBMR_ppp, <span class="dv">1000</span>, <span class="st">"km"</span>)</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(accBMR_ppp.km)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="preparing-events-for-the-network-analysis" class="level2">
<h2 class="anchored" data-anchor-id="preparing-events-for-the-network-analysis">5.10 Preparing events for the network analysis</h2>
<p>spNetwork snaps each event to its nearest road segment. To avoid snapping accidents that lie far from any major road, accidents are kept only if they fall within a 100 m buffer of the major road network.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>road_buffer <span class="ot">&lt;-</span> <span class="fu">st_buffer</span>(network, <span class="at">dist =</span> <span class="dv">100</span>)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>acc_bmr_sf <span class="ot">&lt;-</span> acc_bmr_sf <span class="sc">%&gt;%</span></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">near_road =</span> <span class="fu">lengths</span>(<span class="fu">st_intersects</span>(acc_bmr_sf, road_buffer)) <span class="sc">&gt;</span> <span class="dv">0</span>)</span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(acc_bmr_sf<span class="sc">$</span>near_road)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
FALSE  TRUE 
    5  3594 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>acc_net <span class="ot">&lt;-</span> acc_bmr_sf <span class="sc">%&gt;%</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(near_road)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(acc_bmr_sf, <span class="st">"data/rds/acc_bmr_sf.rds"</span>)</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(acc_net, <span class="st">"data/rds/acc_net.rds"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Before the analysis, the network and the events are plotted together, as in the NetSPAA workflow.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">st_geometry</span>(network))</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">st_geometry</span>(acc_net), <span class="at">add =</span> T, <span class="at">col =</span> <span class="st">'red'</span>, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">cex =</span> <span class="fl">0.3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Interpretation">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Interpretation
</div>
</div>
<div class="callout-body-container callout-body">
<p>Almost all accidents (3,594 of 3,599) lie within 100 m of a major road, which supports treating accidents as events on the major road network. The five excluded accidents are likely on minor roads or mislocated. The plot shows that accidents follow a small number of major roads, while much of the network carries few or no recorded accidents.</p>
</div>
</div>
</section>
</section>
<section id="first-order-point-patterns-analysis" class="level1">
<h1>6. First-order Point Patterns Analysis</h1>
<section id="temporal-variation" class="level2">
<h2 class="anchored" data-anchor-id="temporal-variation">6.1 Temporal variation</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(acc_bmr_sf, <span class="fu">aes</span>(<span class="at">x =</span> Month_num)) <span class="sc">+</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Month (1 = January)"</span>, <span class="at">y =</span> <span class="st">"No. of accidents"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The red dashed lines mark the end of the New Year campaign (4 January, day 4), the Songkran “seven dangerous days” (11-17 April, days 101-107) and the start of the next New Year campaign (29 December, day 363).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(acc_bmr_sf, <span class="fu">aes</span>(<span class="at">x =</span> DayofYear)) <span class="sc">+</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">101</span>, <span class="dv">107</span>, <span class="dv">363</span>),</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">colour =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Day of year, 2022"</span>, <span class="at">y =</span> <span class="st">"No. of accidents per day"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Interpretation">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Interpretation
</div>
</div>
<div class="callout-body-container callout-body">
<p>Recorded accidents vary over time at two scales. Monthly counts range from about 210 in February to about 395 in October, with generally higher counts in the second half of 2022. Daily counts usually fall between 5 and 15, but the most prominent peaks coincide with the New Year and Songkran campaign periods, reaching about 36 accidents at the end of December. These peaks coincide with holiday travel periods, but the data alone cannot show why they occur. Counts are not adjusted for traffic volume, cover only recorded accidents on national roads, and come from a single year, so peaks indicate more recorded accidents rather than necessarily higher risk.</p>
</div>
</div>
</section>
<section id="intensity-by-province" class="level2">
<h2 class="anchored" data-anchor-id="intensity-by-province">6.2 Intensity by province</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>bmr_sf <span class="ot">&lt;-</span> bmr_sf <span class="sc">%&gt;%</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">n_acc =</span> <span class="fu">lengths</span>(<span class="fu">st_intersects</span>(bmr_sf, acc_bmr_sf))) <span class="sc">%&gt;%</span></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">area_km2 =</span> <span class="fu">as.numeric</span>(<span class="fu">st_area</span>(bmr_sf)) <span class="sc">/</span> <span class="dv">1000000</span>) <span class="sc">%&gt;%</span></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">acc_per_km2 =</span> n_acc <span class="sc">/</span> area_km2)</span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>bmr_sf <span class="sc">%&gt;%</span></span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(shapeName, n_acc, area_km2, acc_per_km2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 6 features and 4 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 587130.4 ymin: 1484749 xmax: 712441.7 ymax: 1579087
Projected CRS: WGS 84 / UTM zone 47N
               shapeName n_acc  area_km2 acc_per_km2
1                Bangkok  1802 1570.7019  1.14725779
2 Nakhon Pathom Province   138 2088.4542  0.06607758
3    Nonthaburi Province   174  638.9550  0.27231964
4  Pathum Thani Province   491 1513.6408  0.32438344
5  Samut Sakhon Province   323  839.4175  0.38479063
6  Samut Prakan Province   671  952.9092  0.70415941
                        geometry
1 MULTIPOLYGON (((706791.8 15...
2 MULTIPOLYGON (((643530.5 15...
3 MULTIPOLYGON (((669340.7 15...
4 MULTIPOLYGON (((706784.4 15...
5 MULTIPOLYGON (((644134.6 15...
6 MULTIPOLYGON (((701236.5 15...</code></pre>
</div>
</div>
</section>
<section id="network-kde-nkde" class="level2">
<h2 class="anchored" data-anchor-id="network-kde-nkde">6.3 Network KDE (NKDE)</h2>
<section id="preparing-the-lixels-objects" class="level3">
<h3 class="anchored" data-anchor-id="preparing-the-lixels-objects">6.3.1 Preparing the lixels objects</h3>
<p>Before computing NKDE, the network is cut into lixels. The lixel length is set to 500 m and the minimum length to 250 m, about half of the 1 km bandwidth.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>lixels <span class="ot">&lt;-</span> <span class="fu">lixelize_lines</span>(network,</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>                         <span class="dv">500</span>,</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">mindist =</span> <span class="dv">250</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="generating-line-centre-points" class="level3">
<h3 class="anchored" data-anchor-id="generating-line-centre-points">6.3.2 Generating line centre points</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>samples <span class="ot">&lt;-</span> <span class="fu">lines_center</span>(lixels)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="performing-nkde" class="level3">
<h3 class="anchored" data-anchor-id="performing-nkde">6.3.3 Performing NKDE</h3>
<p>The quartic kernel and the simple method are used, as in the NetSPAA workflow. The bandwidth is 1 km, measured along the network. <code>grid_shape = c(3, 3)</code> splits the large BMR network into a 3 x 3 grid so that the calculation fits in memory; it does not change the result.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>densities <span class="ot">&lt;-</span> <span class="fu">nkde</span>(network,</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">events =</span> acc_net,</span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">w =</span> <span class="fu">rep</span>(<span class="dv">1</span>, <span class="fu">nrow</span>(acc_net)),</span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">samples =</span> samples,</span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">kernel_name =</span> <span class="st">"quartic"</span>,</span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a>                  <span class="at">bw =</span> <span class="dv">1000</span>,</span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a>                  <span class="at">div =</span> <span class="st">"bw"</span>,</span>
<span id="cb62-8"><a href="#cb62-8" aria-hidden="true" tabindex="-1"></a>                  <span class="at">method =</span> <span class="st">"simple"</span>,</span>
<span id="cb62-9"><a href="#cb62-9" aria-hidden="true" tabindex="-1"></a>                  <span class="at">digits =</span> <span class="dv">1</span>,</span>
<span id="cb62-10"><a href="#cb62-10" aria-hidden="true" tabindex="-1"></a>                  <span class="at">tol =</span> <span class="dv">1</span>,</span>
<span id="cb62-11"><a href="#cb62-11" aria-hidden="true" tabindex="-1"></a>                  <span class="at">grid_shape =</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">3</span>),</span>
<span id="cb62-12"><a href="#cb62-12" aria-hidden="true" tabindex="-1"></a>                  <span class="at">max_depth =</span> <span class="dv">8</span>,</span>
<span id="cb62-13"><a href="#cb62-13" aria-hidden="true" tabindex="-1"></a>                  <span class="at">agg =</span> <span class="dv">5</span>,</span>
<span id="cb62-14"><a href="#cb62-14" aria-hidden="true" tabindex="-1"></a>                  <span class="at">sparse =</span> <span class="cn">TRUE</span>,</span>
<span id="cb62-15"><a href="#cb62-15" aria-hidden="true" tabindex="-1"></a>                  <span class="at">verbose =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="visualising-nkde" class="level3">
<h3 class="anchored" data-anchor-id="visualising-nkde">6.3.4 Visualising NKDE</h3>
<p>The density values are inserted into <code>samples</code> and <code>lixels</code>, then rescaled from events per metre to events per kilometre.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>samples<span class="sc">$</span>density <span class="ot">&lt;-</span> densities</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>lixels<span class="sc">$</span>density <span class="ot">&lt;-</span> densities</span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>samples<span class="sc">$</span>density <span class="ot">&lt;-</span> samples<span class="sc">$</span>density <span class="sc">*</span> <span class="dv">1000</span></span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>lixels<span class="sc">$</span>density <span class="ot">&lt;-</span> lixels<span class="sc">$</span>density <span class="sc">*</span> <span class="dv">1000</span></span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(lixels, <span class="st">"data/rds/lixels.rds"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>A static map is used instead of the interactive <code>tmap_mode('view')</code>, because drawing about 60,000 lixels interactively would make the HTML page very large. Road segments with zero density are drawn in grey, so that the coloured segments show where recorded accidents concentrate. Quantile classes are used because most segments have very low values.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>lixels_pos <span class="ot">&lt;-</span> lixels <span class="sc">%&gt;%</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(density <span class="sc">&gt;</span> <span class="dv">0</span>)</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(bmr_sf) <span class="sc">+</span></span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="at">fill =</span> <span class="st">"grey95"</span>) <span class="sc">+</span></span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(network) <span class="sc">+</span></span>
<span id="cb64-7"><a href="#cb64-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_lines</span>(<span class="at">col =</span> <span class="st">"grey80"</span>) <span class="sc">+</span></span>
<span id="cb64-8"><a href="#cb64-8" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(lixels_pos) <span class="sc">+</span></span>
<span id="cb64-9"><a href="#cb64-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_lines</span>(<span class="at">col =</span> <span class="st">"density"</span>,</span>
<span id="cb64-10"><a href="#cb64-10" aria-hidden="true" tabindex="-1"></a>           <span class="at">col.scale =</span> <span class="fu">tm_scale_intervals</span>(<span class="at">style =</span> <span class="st">"quantile"</span>,</span>
<span id="cb64-11"><a href="#cb64-11" aria-hidden="true" tabindex="-1"></a>                                          <span class="at">values =</span> <span class="st">"viridis"</span>),</span>
<span id="cb64-12"><a href="#cb64-12" aria-hidden="true" tabindex="-1"></a>           <span class="at">col.legend =</span> <span class="fu">tm_legend</span>(<span class="at">title =</span> <span class="st">"NKDE (events per km)"</span>),</span>
<span id="cb64-13"><a href="#cb64-13" aria-hidden="true" tabindex="-1"></a>           <span class="at">lwd =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb64-14"><a href="#cb64-14" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_title</span>(<span class="st">"Network KDE of road accidents, BMR 2022"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Interpretation">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Interpretation
</div>
</div>
<div class="callout-body-container callout-body">
<p>NKDE (quartic kernel, 1 km bandwidth measured along the network) estimates accident density on each road segment rather than across continuous space. Density is concentrated on a small number of specific roads: a north–south corridor through eastern Bangkok into Pathum Thani, roads across southern Bangkok into Samut Prakan, where the highest values occur, and a south-western corridor towards Samut Sakhon. Most of the major road network, including much of inner Bangkok, shows zero or near-zero density. Because density is calculated along roads, it identifies particular road segments rather than broad areas, which is more directly useful for targeting interventions. It reflects only accidents recorded by national road agencies, and is not adjusted for traffic volume, so high density does not necessarily mean higher risk.</p>
</div>
</div>
</section>
</section>
<section id="planar-kde-for-comparison" class="level2">
<h2 class="anchored" data-anchor-id="planar-kde-for-comparison">6.4 Planar KDE for comparison</h2>
<p>Planar KDE is computed to compare the network view with the conventional view, in which accidents can occur anywhere in the window.</p>
<section id="automatic-bandwidth-selection" class="level3">
<h3 class="anchored" data-anchor-id="automatic-bandwidth-selection">6.4.1 Automatic bandwidth selection</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bw.diggle</span>(accBMR_ppp.km)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     sigma 
0.02307687 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bw.ppl</span>(accBMR_ppp.km)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>    sigma 
0.7507077 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bw.scott</span>(accBMR_ppp.km)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> sigma.x  sigma.y 
5.238214 4.082151 </code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>kde_accBMR.bw <span class="ot">&lt;-</span> <span class="fu">density</span>(accBMR_ppp.km,</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>                         <span class="at">sigma =</span> bw.diggle,</span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">edge =</span> <span class="cn">TRUE</span>,</span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>                         <span class="at">kernel =</span> <span class="st">"gaussian"</span>)</span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a>kde_accBMR.ppl <span class="ot">&lt;-</span> <span class="fu">density</span>(accBMR_ppp.km,</span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a>                          <span class="at">sigma =</span> bw.ppl,</span>
<span id="cb71-7"><a href="#cb71-7" aria-hidden="true" tabindex="-1"></a>                          <span class="at">edge =</span> <span class="cn">TRUE</span>,</span>
<span id="cb71-8"><a href="#cb71-8" aria-hidden="true" tabindex="-1"></a>                          <span class="at">kernel =</span> <span class="st">"gaussian"</span>)</span>
<span id="cb71-9"><a href="#cb71-9" aria-hidden="true" tabindex="-1"></a>kde_accBMR.scott <span class="ot">&lt;-</span> <span class="fu">density</span>(accBMR_ppp.km,</span>
<span id="cb71-10"><a href="#cb71-10" aria-hidden="true" tabindex="-1"></a>                            <span class="at">sigma =</span> bw.scott,</span>
<span id="cb71-11"><a href="#cb71-11" aria-hidden="true" tabindex="-1"></a>                            <span class="at">edge =</span> <span class="cn">TRUE</span>,</span>
<span id="cb71-12"><a href="#cb71-12" aria-hidden="true" tabindex="-1"></a>                            <span class="at">kernel =</span> <span class="st">"gaussian"</span>)</span>
<span id="cb71-13"><a href="#cb71-13" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>))</span>
<span id="cb71-14"><a href="#cb71-14" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(kde_accBMR.bw, <span class="at">main =</span> <span class="st">"bw.diggle"</span>)</span>
<span id="cb71-15"><a href="#cb71-15" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(kde_accBMR.ppl, <span class="at">main =</span> <span class="st">"bw.ppl"</span>)</span>
<span id="cb71-16"><a href="#cb71-16" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(kde_accBMR.scott, <span class="at">main =</span> <span class="st">"bw.scott"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid figure-img" width="1344"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="bandwidth-sensitivity" class="level3">
<h3 class="anchored" data-anchor-id="bandwidth-sensitivity">6.4.2 Bandwidth sensitivity</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (s <span class="cf">in</span> <span class="fu">c</span>(<span class="fl">0.5</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">5</span>)) {</span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(<span class="fu">density</span>(accBMR_ppp.km,</span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">sigma =</span> s,</span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">edge =</span> <span class="cn">TRUE</span>,</span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a>               <span class="at">kernel =</span> <span class="st">"gaussian"</span>),</span>
<span id="cb72-7"><a href="#cb72-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">main =</span> <span class="fu">paste</span>(<span class="st">"sigma ="</span>, s, <span class="st">"km"</span>))</span>
<span id="cb72-8"><a href="#cb72-8" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="fixed-vs-adaptive-bandwidth" class="level3">
<h3 class="anchored" data-anchor-id="fixed-vs-adaptive-bandwidth">6.4.3 Fixed vs adaptive bandwidth</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>kde_accBMR_adaptive <span class="ot">&lt;-</span> <span class="fu">adaptive.density</span>(accBMR_ppp.km,</span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>                                        <span class="at">method =</span> <span class="st">"kernel"</span>)</span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))</span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(kde_accBMR.ppl, <span class="at">main =</span> <span class="st">"Fixed bandwidth (bw.ppl)"</span>)</span>
<span id="cb73-5"><a href="#cb73-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(kde_accBMR_adaptive, <span class="at">main =</span> <span class="st">"Adaptive bandwidth"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/unnamed-chunk-40-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="mapping-the-selected-planar-kde" class="level3">
<h3 class="anchored" data-anchor-id="mapping-the-selected-planar-kde">6.4.4 Mapping the selected planar KDE</h3>
<p>bw.ppl (0.79 km) is selected. bw.diggle (0.09 km) and the adaptive KDE produce very spiky surfaces dominated by a few sharp peaks, while bw.scott (about 5.2 km x 4.1 km) and the 5 km bandwidth merge the corridors into one broad hotspot. The sensitivity plots show that bandwidths of about 0.5-1 km preserve the corridor structure. For mapping, the KDE is computed on the metre-based ppp object, so that the raster coordinates match EPSG:32647.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>kde_accBMR_m <span class="ot">&lt;-</span> <span class="fu">density</span>(accBMR_ppp,</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>                        <span class="at">sigma =</span> bw.ppl,</span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>                        <span class="at">edge =</span> <span class="cn">TRUE</span>,</span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>                        <span class="at">kernel =</span> <span class="st">"gaussian"</span>)</span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-6"><a href="#cb74-6" aria-hidden="true" tabindex="-1"></a>kde_accBMR_terra <span class="ot">&lt;-</span> <span class="fu">rast</span>(kde_accBMR_m)</span>
<span id="cb74-7"><a href="#cb74-7" aria-hidden="true" tabindex="-1"></a><span class="fu">crs</span>(kde_accBMR_terra) <span class="ot">&lt;-</span> <span class="st">"EPSG:32647"</span></span>
<span id="cb74-8"><a href="#cb74-8" aria-hidden="true" tabindex="-1"></a>kde_accBMR_terra</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>class       : SpatRaster
size        : 128, 128, 1  (nrow, ncol, nlyr)
resolution  : 978.9945, 737.0174  (x, y)
extent      : 587130.4, 712441.7, 1484749, 1579087  (xmin, xmax, ymin, ymax)
coord. ref. : WGS 84 / UTM zone 47N (EPSG:32647)
source(s)   : memory
name        :    lyr.1
min value   :       -0
max value   : 0.000029
unit        : unit</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(kde_accBMR_terra) <span class="sc">+</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_raster</span>(<span class="at">col.scale =</span> <span class="fu">tm_scale_continuous</span>(<span class="at">values =</span> <span class="st">"viridis"</span>),</span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">col.legend =</span> <span class="fu">tm_legend</span>(<span class="at">title =</span> <span class="st">"Density values"</span>)) <span class="sc">+</span></span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(bmr_sf) <span class="sc">+</span></span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">"grey40"</span>) <span class="sc">+</span></span>
<span id="cb76-6"><a href="#cb76-6" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_title</span>(<span class="st">"Planar KDE of road accidents, BMR 2022"</span>) <span class="sc">+</span></span>
<span id="cb76-7"><a href="#cb76-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_graticules</span>(<span class="at">labels.size =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb76-8"><a href="#cb76-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_compass</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Interpretation">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Interpretation
</div>
</div>
<div class="callout-body-container callout-body">
<p>Using the bw.ppl bandwidth (0.79 km), the planar KDE shows the same corridors as the NKDE: a north–south corridor through Bangkok into Pathum Thani, an east–west corridor across southern Bangkok into Samut Prakan, and a south-western corridor towards Samut Sakhon, with the highest intensity in southern Bangkok near the Samut Prakan boundary. The location of these hotspots is stable across bandwidths of 0.5-2 km. However, planar KDE spreads intensity into areas without roads, such as fields and rivers, and cannot show which particular road carries the accidents. Comparing it with Section 6.3 shows that the network view gives the same broad picture but locates it on specific road segments.</p>
</div>
</div>
</section>
</section>
<section id="spatio-temporal-kde-by-month" class="level2">
<h2 class="anchored" data-anchor-id="spatio-temporal-kde-by-month">6.5 Spatio-temporal KDE by month</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>acc_month <span class="ot">&lt;-</span> acc_bmr_sf <span class="sc">%&gt;%</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Month_num)</span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a>acc_month_ppp <span class="ot">&lt;-</span> <span class="fu">as.ppp</span>(acc_month)</span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a>acc_month_owin <span class="ot">&lt;-</span> acc_month_ppp[bmr_owin]</span>
<span id="cb77-5"><a href="#cb77-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(acc_month_owin)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Marked planar point pattern:  3599 points
Average intensity 4.732986e-07 points per square unit

*Pattern contains duplicated points*

Coordinates are given to 10 decimal places

marks are numeric, of type 'double'
Summary:
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  1.000   4.000   7.000   6.994  10.000  12.000 

Window: polygonal boundary
single connected closed polygon with 1699 vertices
enclosing rectangle: [587130.4, 712441.7] x [1484748.9, 1579087.2] units
                     (125300 x 94340 units)
Window area = 7604080000 square units
Fraction of frame area: 0.643</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>st_kde <span class="ot">&lt;-</span> <span class="fu">spattemp.density</span>(acc_month_owin)</span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(st_kde)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Spatiotemporal Kernel Density Estimate

Bandwidths
  h = 4882.467 (spatial)
  lambda = 0.0285 (temporal)

No. of observations
  3599 

Spatial bound
  Type: polygonal
  2D enclosure: [587130.4, 712441.7] x [1484749, 1579087]

Temporal bound
  [1, 12]

Evaluation
  128 x 128 x 12 trivariate lattice
  Density range: [9.448582e-22, 2.845214e-09]</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>tims <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">7</span>, <span class="dv">8</span>, <span class="dv">9</span>, <span class="dv">10</span>, <span class="dv">11</span>, <span class="dv">12</span>)</span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfcol =</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">4</span>))</span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> tims) {</span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(st_kde, i,</span>
<span id="cb81-5"><a href="#cb81-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">override.par =</span> <span class="cn">FALSE</span>,</span>
<span id="cb81-6"><a href="#cb81-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">fix.range =</span> <span class="cn">TRUE</span>,</span>
<span id="cb81-7"><a href="#cb81-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">main =</span> <span class="fu">paste</span>(<span class="st">"KDE at month"</span>, i))</span>
<span id="cb81-8"><a href="#cb81-8" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/unnamed-chunk-45-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Interpretation">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Interpretation
</div>
</div>
<div class="callout-body-container callout-body">
<p>The spatio-temporal KDE shows that the location of the main accident hotspot, in south-eastern Bangkok near the Samut Prakan boundary, is stable throughout 2022, while its intensity varies by month. Intensity is highest in December and relatively high in January, and lowest in February, March, May and June, consistent with the monthly counts in Section 6.1. From around August, a secondary concentration towards Samut Sakhon also becomes more visible. The automatically selected spatial bandwidth (about 4.9 km) is large, so these maps show broad hotspots rather than individual road corridors. The temporal bandwidth is very small relative to the monthly time unit, so each panel mainly reflects that month’s accidents. Monthly aggregation may also hide short peaks such as the Songkran week.</p>
</div>
</div>
</section>
<section id="spatio-temporal-kde-by-day-of-year" class="level2">
<h2 class="anchored" data-anchor-id="spatio-temporal-kde-by-day-of-year">6.6 Spatio-temporal KDE by day of year</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>acc_yday_ppp <span class="ot">&lt;-</span> acc_bmr_sf <span class="sc">%&gt;%</span></span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(DayofYear) <span class="sc">%&gt;%</span></span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.ppp</span>()</span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a>acc_yday_owin <span class="ot">&lt;-</span> acc_yday_ppp[bmr_owin]</span>
<span id="cb82-5"><a href="#cb82-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(acc_yday_owin)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Marked planar point pattern:  3599 points
Average intensity 4.732986e-07 points per square unit

*Pattern contains duplicated points*

Coordinates are given to 10 decimal places

marks are numeric, of type 'double'
Summary:
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    1.0   104.0   208.0   197.5   292.0   365.0 

Window: polygonal boundary
single connected closed polygon with 1699 vertices
enclosing rectangle: [587130.4, 712441.7] x [1484748.9, 1579087.2] units
                     (125300 x 94340 units)
Window area = 7604080000 square units
Fraction of frame area: 0.643</code></pre>
</div>
</div>
<p><code>BOOT.spattemp()</code> selects the spatial and temporal bandwidths by bootstrap.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a><span class="fu">BOOT.spattemp</span>(acc_yday_owin)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Initialising...Done.
Optimising...
h = 4882.467 ; lambda = 23.86965 
h = 5370.714 ; lambda = 23.86965 
h = 4882.467 ; lambda = 512.1164 
h = 5004.529 ; lambda = 267.993 
h = 5065.56 ; lambda = 145.9313 
h = 5096.075 ; lambda = 84.90049 
h = 4607.828 ; lambda = 84.90049 
h = 4226.386 ; lambda = 115.4159 
h = 4439.994 ; lambda = 176.4468 
h = 4771.849 ; lambda = 62.01392 
h = 3902.159 ; lambda = 92.52934 
h = 3305.201 ; lambda = 96.34377 
h = 2759.738 ; lambda = 149.7458 
h = 3262.766 ; lambda = 127.8128 
h = 2341.582 ; lambda = 108.7407 
h = 2812.783 ; lambda = 110.4095 
h = 2855.218 ; lambda = 78.94045 
h = 2651.444 ; lambda = 54.50427 
h = 3347.637 ; lambda = 64.87474 
h = 3213.923 ; lambda = 76.25843 
h = 2763.94 ; lambda = 58.8551 
h = 3169.886 ; lambda = 86.9716 
h = 2899.255 ; lambda = 68.22727 
h = 2966.913 ; lambda = 72.91335 
h = 2608.208 ; lambda = 75.59537 
h = 3062.495 ; lambda = 76.09266 
Done.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>         h     lambda 
3062.49456   76.09266 </code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="co"># </span><span class="al">TODO</span><span class="co">: check h and lambda against the BOOT.spattemp() output above;</span></span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a><span class="co"># they were 3061.77 and 76.07 in the earlier run, and may change slightly</span></span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a>kde_yday <span class="ot">&lt;-</span> <span class="fu">spattemp.density</span>(acc_yday_owin,</span>
<span id="cb87-4"><a href="#cb87-4" aria-hidden="true" tabindex="-1"></a>                             <span class="at">h =</span> <span class="dv">3062</span>,</span>
<span id="cb87-5"><a href="#cb87-5" aria-hidden="true" tabindex="-1"></a>                             <span class="at">lambda =</span> <span class="dv">76</span>)</span>
<span id="cb87-6"><a href="#cb87-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(kde_yday)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Spatiotemporal Kernel Density Estimate

Bandwidths
  h = 3062 (spatial)
  lambda = 76 (temporal)

No. of observations
  3599 

Spatial bound
  Type: polygonal
  2D enclosure: [587130.4, 712441.7] x [1484749, 1579087]

Temporal bound
  [1, 365]

Evaluation
  128 x 128 x 365 trivariate lattice
  Density range: [7.881223e-19, 5.140111e-12]</code></pre>
</div>
</div>
<p>The four days shown are mid-February, mid-April, mid-July and mid-October. Days near the start and end of the year are avoided because estimates there are affected by the temporal boundary.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a>tims <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">46</span>, <span class="dv">105</span>, <span class="dv">196</span>, <span class="dv">288</span>)</span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfcol =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> tims) {</span>
<span id="cb89-4"><a href="#cb89-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(kde_yday, i,</span>
<span id="cb89-5"><a href="#cb89-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">override.par =</span> <span class="cn">FALSE</span>,</span>
<span id="cb89-6"><a href="#cb89-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">fix.range =</span> <span class="cn">TRUE</span>,</span>
<span id="cb89-7"><a href="#cb89-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">main =</span> <span class="fu">paste</span>(<span class="st">"KDE at day"</span>, i))</span>
<span id="cb89-8"><a href="#cb89-8" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/unnamed-chunk-49-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Interpretation">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Interpretation
</div>
</div>
<div class="callout-body-container callout-body">
<p>Using day of year with bootstrap-selected bandwidths (h ≈ 3.1 km, lambda ≈ 76 days), the STKDE shows a stable core and a changing periphery. The main hotspot in south-eastern Bangkok near the Samut Prakan boundary, and the north–south corridor into Pathum Thani, persist throughout 2022. In contrast, the south-western corridor towards Samut Sakhon is faint in February and April but becomes increasingly prominent in July and October, when overall intensity is also higher, consistent with the monthly counts in Section 6.1. However, the 76-day temporal bandwidth pools accidents over roughly two to three months, so short-lived peaks such as the Songkran and New Year holidays are smoothed out; the daily graphic in Section 6.1 remains the evidence for those peaks.</p>
</div>
</div>
</section>
</section>
<section id="second-order-point-patterns-analysis" class="level1">
<h1>7. Second-order Point Patterns Analysis</h1>
<section id="network-k--and-g-function-analysis" class="level2">
<h2 class="anchored" data-anchor-id="network-k--and-g-function-analysis">7.1 Network K- and G-function analysis</h2>
<p><strong>Research question:</strong> after accounting for the fact that accidents can only occur on the road network, are accidents clustered, regular or approximately random along the network?</p>
<p><strong>Hypotheses:</strong></p>
<p>H0: The observed accidents are uniformly distributed over the major road network in Bangkok.</p>
<p>H1: The observed accidents are not uniformly distributed over the major road network in Bangkok.</p>
<p>The CSR test is based on the binomial point process, which assumes accidents are randomly and independently distributed over the network. If H0 is rejected, accidents may be spatially interacting and dependent on each other, forming non-random patterns.</p>
<p>The analysis is restricted to Bangkok, because simulating random points on the full BMR network is very slow. <code>kfunctions()</code> computes both the network K-function and the network G-function, and compares them with 50 simulations of random points on the network.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a>bkk_sf <span class="ot">&lt;-</span> bmr_sf <span class="sc">%&gt;%</span></span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(shapeName <span class="sc">==</span> <span class="st">"Bangkok"</span>)</span>
<span id="cb90-3"><a href="#cb90-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb90-4"><a href="#cb90-4" aria-hidden="true" tabindex="-1"></a>network_bkk <span class="ot">&lt;-</span> network <span class="sc">%&gt;%</span></span>
<span id="cb90-5"><a href="#cb90-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">lengths</span>(<span class="fu">st_intersects</span>(network, bkk_sf)) <span class="sc">&gt;</span> <span class="dv">0</span>)</span>
<span id="cb90-6"><a href="#cb90-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb90-7"><a href="#cb90-7" aria-hidden="true" tabindex="-1"></a>acc_bkk <span class="ot">&lt;-</span> acc_net <span class="sc">%&gt;%</span></span>
<span id="cb90-8"><a href="#cb90-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">lengths</span>(<span class="fu">st_intersects</span>(acc_net, bkk_sf)) <span class="sc">&gt;</span> <span class="dv">0</span>)</span>
<span id="cb90-9"><a href="#cb90-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb90-10"><a href="#cb90-10" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(acc_bkk)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1801</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a>kfun_acc <span class="ot">&lt;-</span> <span class="fu">kfunctions</span>(network_bkk,</span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a>                       acc_bkk,</span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">start =</span> <span class="dv">0</span>,</span>
<span id="cb92-4"><a href="#cb92-4" aria-hidden="true" tabindex="-1"></a>                       <span class="at">end =</span> <span class="dv">5000</span>,</span>
<span id="cb92-5"><a href="#cb92-5" aria-hidden="true" tabindex="-1"></a>                       <span class="at">step =</span> <span class="dv">100</span>,</span>
<span id="cb92-6"><a href="#cb92-6" aria-hidden="true" tabindex="-1"></a>                       <span class="at">width =</span> <span class="dv">200</span>,</span>
<span id="cb92-7"><a href="#cb92-7" aria-hidden="true" tabindex="-1"></a>                       <span class="at">nsim =</span> <span class="dv">50</span>,</span>
<span id="cb92-8"><a href="#cb92-8" aria-hidden="true" tabindex="-1"></a>                       <span class="at">resolution =</span> <span class="dv">50</span>,</span>
<span id="cb92-9"><a href="#cb92-9" aria-hidden="true" tabindex="-1"></a>                       <span class="at">verbose =</span> <span class="cn">FALSE</span>,</span>
<span id="cb92-10"><a href="#cb92-10" aria-hidden="true" tabindex="-1"></a>                       <span class="at">conf_int =</span> <span class="fl">0.05</span>)</span>
<span id="cb92-11"><a href="#cb92-11" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(kfun_acc, <span class="st">"data/rds/kfun_acc.rds"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a>kfun_acc <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/rds/kfun_acc.rds"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The blue line is the empirical network K-function and the grey envelope shows the 2.5%-97.5% interval of the 50 simulations. A blue line above the envelope indicates clustering at that distance, and below it indicates regularity.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a>kfun_acc<span class="sc">$</span>plotk</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/unnamed-chunk-53-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The network G-function counts pairs of accidents within each 200 m ring, so it shows at which specific distances clustering or regularity occurs.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a>kfun_acc<span class="sc">$</span>plotg</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/unnamed-chunk-54-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Interpretation">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Interpretation
</div>
</div>
<div class="callout-body-container callout-body">
<!-- TODO: write after running. State the distance ranges where the blue line is above, inside or below the envelope, for both the K- and G-functions. -->
</div>
</div>
</section>
<section id="planar-tests-against-csr-for-comparison" class="level2">
<h2 class="anchored" data-anchor-id="planar-tests-against-csr-for-comparison">7.2 Planar tests against CSR, for comparison</h2>
<p>These tests use planar CSR as the null model: accidents are assumed equally likely anywhere in BMR, including where there are no roads. They are included to show how much the conclusion depends on the null model.</p>
<p>H0: accidents are randomly distributed in BMR (CSR). H1: accidents are clustered.</p>
<section id="clark-evans-test" class="level3">
<h3 class="anchored" data-anchor-id="clark-evans-test">7.2.1 Clark-Evans test</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">clarkevans.test</span>(accBMR_ppp.km,</span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">correction =</span> <span class="st">"none"</span>,</span>
<span id="cb96-3"><a href="#cb96-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">clipregion =</span> <span class="cn">NULL</span>,</span>
<span id="cb96-4"><a href="#cb96-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">alternative =</span> <span class="fu">c</span>(<span class="st">"clustered"</span>),</span>
<span id="cb96-5"><a href="#cb96-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">method =</span> <span class="st">"MonteCarlo"</span>,</span>
<span id="cb96-6"><a href="#cb96-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">nsim =</span> <span class="dv">99</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Clark-Evans test
    No edge correction
    Monte Carlo test based on 99 simulations of CSR with fixed n

data:  accBMR_ppp.km
R = 0.26518, p-value = 0.01
alternative hypothesis: clustered (R &lt; 1)</code></pre>
</div>
</div>
</section>
<section id="g-function" class="level3">
<h3 class="anchored" data-anchor-id="g-function">7.2.2 G-function</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a>G_acc.csr <span class="ot">&lt;-</span> <span class="fu">envelope</span>(accBMR_ppp.km, Gest, <span class="at">nsim =</span> <span class="dv">99</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Generating 99 simulated realisations of CSR  ...
1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 
99.

Done.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(G_acc.csr, <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">2</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/unnamed-chunk-56-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="l-function" class="level3">
<h3 class="anchored" data-anchor-id="l-function">7.2.3 L-function</h3>
<p>With 99 simulations and <code>rank = 1</code>, the global envelope corresponds to a significance level of 0.01.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a>L_acc.csr <span class="ot">&lt;-</span> <span class="fu">envelope</span>(accBMR_ppp.km, Lest, <span class="at">nsim =</span> <span class="dv">99</span>, <span class="at">rank =</span> <span class="dv">1</span>, <span class="at">glocal =</span> <span class="cn">TRUE</span>)</span>
<span id="cb101-2"><a href="#cb101-2" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(L_acc.csr, <span class="st">"data/rds/L_acc_csr.rds"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a>L_acc.csr <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/rds/L_acc_csr.rds"</span>)</span>
<span id="cb102-2"><a href="#cb102-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(L_acc.csr, . <span class="sc">-</span> r <span class="sc">~</span> r, <span class="at">xlab =</span> <span class="st">"d (km)"</span>, <span class="at">ylab =</span> <span class="st">"L(d)-r"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/unnamed-chunk-58-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Interpretation">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Interpretation
</div>
</div>
<div class="callout-body-container callout-body">
<p>Against planar CSR, all tests indicate strong clustering: the Clark-Evans ratio is well below 1 (<!-- TODO: R value -->, p = 0.01), and the G- and L-functions lie far above their envelopes. The G-function also jumps at distance 0, because accidents sharing exact locations have a nearest-neighbour distance of zero. However, planar CSR assumes accidents can occur anywhere in BMR, whereas Sections 5.10 and 6.3 show they are confined to a small number of roads. Much of this apparent clustering therefore reflects the road network itself. This is why the network K-function in Section 7.1, which uses CSR on the network as the null model, is the main second-order test in this study.</p>
</div>
</div>
</section>
</section>
<section id="spatio-temporal-k-function" class="level2">
<h2 class="anchored" data-anchor-id="spatio-temporal-k-function">7.3 Spatio-temporal K-function</h2>
<p><strong>Research question:</strong> do accidents that are close in space also tend to be close in time?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a>coords <span class="ot">&lt;-</span> <span class="fu">st_coordinates</span>(acc_bmr_sf)</span>
<span id="cb103-2"><a href="#cb103-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb103-3"><a href="#cb103-3" aria-hidden="true" tabindex="-1"></a>acc_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb103-4"><a href="#cb103-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> coords[, <span class="dv">1</span>],</span>
<span id="cb103-5"><a href="#cb103-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> coords[, <span class="dv">2</span>],</span>
<span id="cb103-6"><a href="#cb103-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">t =</span> acc_bmr_sf<span class="sc">$</span>DayofYear)</span>
<span id="cb103-7"><a href="#cb103-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb103-8"><a href="#cb103-8" aria-hidden="true" tabindex="-1"></a>acc_stpp <span class="ot">&lt;-</span> <span class="fu">as.3dpoints</span>(acc_df)</span>
<span id="cb103-9"><a href="#cb103-9" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(acc_stpp)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "stpp"</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb105-2"><a href="#cb105-2" aria-hidden="true" tabindex="-1"></a>acc_stik <span class="ot">&lt;-</span> <span class="fu">STIKhat</span>(acc_stpp)</span>
<span id="cb105-3"><a href="#cb105-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plotK</span>(acc_stik)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Interpretation">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Interpretation
</div>
</div>
<div class="callout-body-container callout-body">
<!-- TODO: write after running. High contour values at small spatial (u) and temporal (v) distances suggest clustering in both space and time. Note that STIKhat assumes constant intensity, so it cannot separate interaction from uneven intensity. -->
</div>
</div>
</section>
</section>
<section id="value-added-analysis-sensitivity-of-nkde-to-bandwidth" class="level1">
<h1>8. Value-added Analysis: Sensitivity of NKDE to Bandwidth</h1>
<p><strong>Research question:</strong> are the high-density road segments identified in Section 6.3 robust to the choice of NKDE bandwidth?</p>
<p>The NKDE is recomputed with bandwidths of 500 m and 2 km, using the same lixels, samples and settings as Section 6.3.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a>densities_500 <span class="ot">&lt;-</span> <span class="fu">nkde</span>(network,</span>
<span id="cb106-2"><a href="#cb106-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">events =</span> acc_net,</span>
<span id="cb106-3"><a href="#cb106-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">w =</span> <span class="fu">rep</span>(<span class="dv">1</span>, <span class="fu">nrow</span>(acc_net)),</span>
<span id="cb106-4"><a href="#cb106-4" aria-hidden="true" tabindex="-1"></a>                      <span class="at">samples =</span> samples,</span>
<span id="cb106-5"><a href="#cb106-5" aria-hidden="true" tabindex="-1"></a>                      <span class="at">kernel_name =</span> <span class="st">"quartic"</span>,</span>
<span id="cb106-6"><a href="#cb106-6" aria-hidden="true" tabindex="-1"></a>                      <span class="at">bw =</span> <span class="dv">500</span>,</span>
<span id="cb106-7"><a href="#cb106-7" aria-hidden="true" tabindex="-1"></a>                      <span class="at">div =</span> <span class="st">"bw"</span>,</span>
<span id="cb106-8"><a href="#cb106-8" aria-hidden="true" tabindex="-1"></a>                      <span class="at">method =</span> <span class="st">"simple"</span>,</span>
<span id="cb106-9"><a href="#cb106-9" aria-hidden="true" tabindex="-1"></a>                      <span class="at">digits =</span> <span class="dv">1</span>,</span>
<span id="cb106-10"><a href="#cb106-10" aria-hidden="true" tabindex="-1"></a>                      <span class="at">tol =</span> <span class="dv">1</span>,</span>
<span id="cb106-11"><a href="#cb106-11" aria-hidden="true" tabindex="-1"></a>                      <span class="at">grid_shape =</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">3</span>),</span>
<span id="cb106-12"><a href="#cb106-12" aria-hidden="true" tabindex="-1"></a>                      <span class="at">max_depth =</span> <span class="dv">8</span>,</span>
<span id="cb106-13"><a href="#cb106-13" aria-hidden="true" tabindex="-1"></a>                      <span class="at">agg =</span> <span class="dv">5</span>,</span>
<span id="cb106-14"><a href="#cb106-14" aria-hidden="true" tabindex="-1"></a>                      <span class="at">sparse =</span> <span class="cn">TRUE</span>,</span>
<span id="cb106-15"><a href="#cb106-15" aria-hidden="true" tabindex="-1"></a>                      <span class="at">verbose =</span> <span class="cn">FALSE</span>)</span>
<span id="cb106-16"><a href="#cb106-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb106-17"><a href="#cb106-17" aria-hidden="true" tabindex="-1"></a>densities_2000 <span class="ot">&lt;-</span> <span class="fu">nkde</span>(network,</span>
<span id="cb106-18"><a href="#cb106-18" aria-hidden="true" tabindex="-1"></a>                       <span class="at">events =</span> acc_net,</span>
<span id="cb106-19"><a href="#cb106-19" aria-hidden="true" tabindex="-1"></a>                       <span class="at">w =</span> <span class="fu">rep</span>(<span class="dv">1</span>, <span class="fu">nrow</span>(acc_net)),</span>
<span id="cb106-20"><a href="#cb106-20" aria-hidden="true" tabindex="-1"></a>                       <span class="at">samples =</span> samples,</span>
<span id="cb106-21"><a href="#cb106-21" aria-hidden="true" tabindex="-1"></a>                       <span class="at">kernel_name =</span> <span class="st">"quartic"</span>,</span>
<span id="cb106-22"><a href="#cb106-22" aria-hidden="true" tabindex="-1"></a>                       <span class="at">bw =</span> <span class="dv">2000</span>,</span>
<span id="cb106-23"><a href="#cb106-23" aria-hidden="true" tabindex="-1"></a>                       <span class="at">div =</span> <span class="st">"bw"</span>,</span>
<span id="cb106-24"><a href="#cb106-24" aria-hidden="true" tabindex="-1"></a>                       <span class="at">method =</span> <span class="st">"simple"</span>,</span>
<span id="cb106-25"><a href="#cb106-25" aria-hidden="true" tabindex="-1"></a>                       <span class="at">digits =</span> <span class="dv">1</span>,</span>
<span id="cb106-26"><a href="#cb106-26" aria-hidden="true" tabindex="-1"></a>                       <span class="at">tol =</span> <span class="dv">1</span>,</span>
<span id="cb106-27"><a href="#cb106-27" aria-hidden="true" tabindex="-1"></a>                       <span class="at">grid_shape =</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">3</span>),</span>
<span id="cb106-28"><a href="#cb106-28" aria-hidden="true" tabindex="-1"></a>                       <span class="at">max_depth =</span> <span class="dv">8</span>,</span>
<span id="cb106-29"><a href="#cb106-29" aria-hidden="true" tabindex="-1"></a>                       <span class="at">agg =</span> <span class="dv">5</span>,</span>
<span id="cb106-30"><a href="#cb106-30" aria-hidden="true" tabindex="-1"></a>                       <span class="at">sparse =</span> <span class="cn">TRUE</span>,</span>
<span id="cb106-31"><a href="#cb106-31" aria-hidden="true" tabindex="-1"></a>                       <span class="at">verbose =</span> <span class="cn">FALSE</span>)</span>
<span id="cb106-32"><a href="#cb106-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb106-33"><a href="#cb106-33" aria-hidden="true" tabindex="-1"></a>lixels<span class="sc">$</span>density_500 <span class="ot">&lt;-</span> densities_500 <span class="sc">*</span> <span class="dv">1000</span></span>
<span id="cb106-34"><a href="#cb106-34" aria-hidden="true" tabindex="-1"></a>lixels<span class="sc">$</span>density_2000 <span class="ot">&lt;-</span> densities_2000 <span class="sc">*</span> <span class="dv">1000</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a>map_500 <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(network) <span class="sc">+</span></span>
<span id="cb107-2"><a href="#cb107-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_lines</span>(<span class="at">col =</span> <span class="st">"grey80"</span>) <span class="sc">+</span></span>
<span id="cb107-3"><a href="#cb107-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(lixels <span class="sc">%&gt;%</span> <span class="fu">filter</span>(density_500 <span class="sc">&gt;</span> <span class="dv">0</span>)) <span class="sc">+</span></span>
<span id="cb107-4"><a href="#cb107-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_lines</span>(<span class="at">col =</span> <span class="st">"density_500"</span>,</span>
<span id="cb107-5"><a href="#cb107-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">col.scale =</span> <span class="fu">tm_scale_intervals</span>(<span class="at">style =</span> <span class="st">"quantile"</span>,</span>
<span id="cb107-6"><a href="#cb107-6" aria-hidden="true" tabindex="-1"></a>                                          <span class="at">values =</span> <span class="st">"viridis"</span>),</span>
<span id="cb107-7"><a href="#cb107-7" aria-hidden="true" tabindex="-1"></a>           <span class="at">col.legend =</span> <span class="fu">tm_legend</span>(<span class="at">title =</span> <span class="st">"NKDE, bw = 500 m"</span>),</span>
<span id="cb107-8"><a href="#cb107-8" aria-hidden="true" tabindex="-1"></a>           <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb107-9"><a href="#cb107-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb107-10"><a href="#cb107-10" aria-hidden="true" tabindex="-1"></a>map_2000 <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(network) <span class="sc">+</span></span>
<span id="cb107-11"><a href="#cb107-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_lines</span>(<span class="at">col =</span> <span class="st">"grey80"</span>) <span class="sc">+</span></span>
<span id="cb107-12"><a href="#cb107-12" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(lixels <span class="sc">%&gt;%</span> <span class="fu">filter</span>(density_2000 <span class="sc">&gt;</span> <span class="dv">0</span>)) <span class="sc">+</span></span>
<span id="cb107-13"><a href="#cb107-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_lines</span>(<span class="at">col =</span> <span class="st">"density_2000"</span>,</span>
<span id="cb107-14"><a href="#cb107-14" aria-hidden="true" tabindex="-1"></a>           <span class="at">col.scale =</span> <span class="fu">tm_scale_intervals</span>(<span class="at">style =</span> <span class="st">"quantile"</span>,</span>
<span id="cb107-15"><a href="#cb107-15" aria-hidden="true" tabindex="-1"></a>                                          <span class="at">values =</span> <span class="st">"viridis"</span>),</span>
<span id="cb107-16"><a href="#cb107-16" aria-hidden="true" tabindex="-1"></a>           <span class="at">col.legend =</span> <span class="fu">tm_legend</span>(<span class="at">title =</span> <span class="st">"NKDE, bw = 2 km"</span>),</span>
<span id="cb107-17"><a href="#cb107-17" aria-hidden="true" tabindex="-1"></a>           <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb107-18"><a href="#cb107-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb107-19"><a href="#cb107-19" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(map_500, map_2000, <span class="at">ncol =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/unnamed-chunk-62-1.png" class="img-fluid figure-img" width="1344"></p>
</figure>
</div>
</div>
</div>
<p>The summary statistics show how the range of density values changes with the bandwidth.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lixels<span class="sc">$</span>density_500)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
0.0000000 0.0000000 0.0000000 0.0009199 0.0000000 0.1394506 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb110"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lixels<span class="sc">$</span>density)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
0.000000 0.000000 0.000000 0.000577 0.000415 0.042352 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb112"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lixels<span class="sc">$</span>density_2000)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
0.000e+00 0.000e+00 6.496e-05 4.455e-04 4.375e-04 1.725e-02 </code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Interpretation">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Interpretation
</div>
</div>
<div class="callout-body-container callout-body">
<!-- TODO: write after running. State whether the same corridors appear at all three bandwidths (compare with the 1 km map in Section 6.3), and how the maximum density changes. -->
</div>
</div>
</section>
<section id="integrated-findings-and-discussion" class="level1">
<h1>9. Integrated Findings and Discussion</h1>
<p><strong>What does the first-order analysis reveal?</strong> Recorded accidents are highly uneven in space and time. NKDE shows that density is confined to a small number of specific roads, particularly corridors across southern Bangkok into Samut Prakan, into Pathum Thani and towards Samut Sakhon (Section 6.3); planar KDE shows the same corridors (Section 6.4). Temporally, counts are higher in the second half of 2022 (peaking in October) and spike during the New Year and Songkran campaign periods (Section 6.1), while the hotspot locations are stable through the year (Sections 6.5 and 6.6).</p>
<p><strong>What does the second-order analysis reveal?</strong> Against planar CSR, accidents are strongly clustered at all distances tested (Section 7.2). Against CSR on the road network, <!-- TODO: summarise the network K- and G-function result from Section 7.1 -->.</p>
<p><strong>How do they complement each other?</strong> The first-order results show that accidents are concentrated on a few roads, which explains much of the strong planar clustering. The network second-order test asks whether, along those roads, accidents are closer together than random placement on the network would produce. <!-- TODO: one sentence linking the network K result to the repeated locations in Section 5.9. --></p>
<p><strong>Are the findings consistent across analytical views?</strong> The location of the main corridors is consistent across NKDE, planar KDE at 0.5-2 km bandwidths, and spatio-temporal KDE. The strength of clustering is not: it depends strongly on whether the null model is planar CSR or CSR on the network. <!-- TODO: add the NKDE bandwidth sensitivity result from Section 8. --></p>
<p><strong>What assumptions or limitations matter?</strong> The most important are the observation process (only national road agencies’ records), the absence of traffic-volume data, the restriction of the network K-function to Bangkok, and sensitivity to bandwidth; these are detailed in Section 11.</p>
<p><strong>Are there alternative explanations?</strong> Concentrations along corridors may reflect higher traffic volumes rather than higher risk per vehicle; network CSR assumes equal exposure on every road, which is unlikely. Repeated locations may partly reflect recording practices, such as locating accidents at fixed reference points, rather than true hotspots. Low intensity in inner Bangkok may reflect missing records from city-managed streets rather than safer roads.</p>
</section>
<section id="public-safety-planning-and-management-implications" class="level1">
<h1>10. Public-safety Planning and Management Implications</h1>
<section id="supported-directly-by-the-analysis" class="level2">
<h2 class="anchored" data-anchor-id="supported-directly-by-the-analysis">Supported directly by the analysis</h2>
<p><strong>Prioritising road segments rather than areas.</strong> NKDE shows that recorded accidents are concentrated on a small number of specific roads, particularly the corridors across southern Bangkok into Samut Prakan, the north–south corridor into Pathum Thani, and the south-western corridor towards Samut Sakhon. Road-safety audits, enforcement and engineering reviews can therefore be targeted at identified road segments rather than spread evenly across provinces.</p>
<p><strong>Focusing on repeated locations.</strong> Some accidents share exact locations (Section 5.9). These locations are natural candidates for site-level investigation, such as junction design, signage and lighting.</p>
<p><strong>Timing interventions.</strong> Accidents are more frequent in the second half of the year and during the New Year and Songkran periods. Enforcement and campaign resources can be scheduled to match these periods.</p>
<p><strong>Monitoring emerging corridors.</strong> The south-western corridor towards Samut Sakhon becomes more prominent from mid-year onwards (Section 6.6), suggesting it should be monitored over future years to see whether this pattern persists.</p>
<p><strong>Emergency response.</strong> Because accidents are concentrated along identifiable road segments, the locations of ambulance and rescue units can be evaluated against these segments, for example by checking response distances along the network.</p>
</section>
<section id="requiring-additional-information" class="level2">
<h2 class="anchored" data-anchor-id="requiring-additional-information">Requiring additional information</h2>
<p><strong>Assessing risk rather than counts.</strong> The analysis identifies where recorded accidents concentrate, not where roads are most dangerous. Traffic volume data would be needed to convert counts into accident rates per vehicle-kilometre before concluding that a road segment is high-risk.</p>
<p><strong>Explaining causes.</strong> The analysis does not show why accidents concentrate on these roads or at these times. Attributes such as presumed cause, vehicle type and road design, together with field inspections, would be needed before designing specific engineering or behavioural interventions.</p>
<p><strong>Covering city streets.</strong> All records come from national road agencies. Integrating data from the Bangkok Metropolitan Administration would be necessary before drawing conclusions about inner Bangkok, where low intensity may reflect missing records.</p>
<p><strong>Evaluating interventions.</strong> Multi-year data (for example, 2019–2022) would be needed to confirm whether the identified corridors and seasonal patterns are stable, and to evaluate whether past campaigns have had any effect.</p>
</section>
</section>
<section id="limitations" class="level1">
<h1>11. Limitations</h1>
<ul>
<li><strong>Observation process.</strong> All records come from national road agencies (Department of Highways 80.1%, Expressway Authority 13.1%, Department of Rural Roads 6.8%). Accidents on city-managed streets are likely missing, so patterns describe recorded accidents on these road types only.</li>
<li><strong>No exposure data.</strong> Without traffic volumes, concentrations cannot be interpreted as higher risk, and network CSR assumes equal exposure on all roads.</li>
<li><strong>Location quality.</strong> 189 records lacked coordinates, and some accidents share exact locations, possibly reflecting fixed reference points. These were kept, which inflates the planar G-function at distance zero.</li>
<li><strong>Single year.</strong> Only 2022 is analysed, so patterns may not be stable across years.</li>
<li><strong>Bandwidth sensitivity.</strong> Planar KDE and NKDE depend on bandwidth; results were compared at several bandwidths, but not all choices can be exhausted.</li>
<li><strong>Limited simulations and extent.</strong> The network K-function uses 50 simulations and covers Bangkok only, for computational reasons.</li>
<li><strong>Temporal smoothing.</strong> The day-of-year STKDE uses a 76-day temporal bandwidth, which smooths out short holiday peaks; the space–time K-function assumes constant intensity.</li>
<li><strong>Network data.</strong> The OSM road network is a 2026 extract, whereas accidents are from 2022, and only major road classes were included. Roads built after 2022 appear in the network without any accidents.</li>
<li><strong>Study window.</strong> BMR is defined by six provincial boundaries; a different definition of the metropolitan area could change edge effects and intensity estimates.</li>
</ul>
</section>
<section id="references" class="level1">
<h1>12. References</h1>
<ul>
<li>Asian Transport Observatory. (2025). <em>Thailand Road Safety Profile 2025</em>.</li>
<li>Baddeley, A., Rubak, E., &amp; Turner, R. (2015). <em>Spatial Point Patterns: Methodology and Applications with R</em>. Chapman and Hall/CRC.</li>
<li>Davies, T. M., Marshall, J. C., &amp; Hazelton, M. L. (2018). Tutorial on kernel estimation of continuous spatial and spatiotemporal relative risk. <em>Statistics in Medicine</em>, 37(7), 1191-1221.</li>
<li>Gabriel, E., Rowlingson, B. S., &amp; Diggle, P. J. (2013). stpp: An R package for plotting, simulating and analyzing spatio-temporal point patterns. <em>Journal of Statistical Software</em>, 53(2), 1-29.</li>
<li>Gelb, J. (2021). spNetwork: A package for network kernel density estimation. <em>The R Journal</em>, 13(2), 102-116.</li>
<li>Kam, T. S. <em>R for Geospatial Data Science and Analytics</em>, Chapter 7: Network Constrained Spatial Point Patterns Analysis. https://r4gdsa.netlify.app/chap07</li>
<li>Okabe, A., &amp; Sugihara, K. (2012). <em>Spatial Analysis along Networks: Statistical and Computational Methods</em>. Wiley.</li>
<li>OpenStreetMap contributors. Thailand extract via Geofabrik, 21 September 2026.</li>
<li>Runfola, D. et al.&nbsp;(2020). geoBoundaries: A global database of political administrative boundaries. <em>PLOS ONE</em>, 15(4), e0231866.</li>
<li>Thaweewat R. Thailand Road Accident [2019-2022]. Kaggle.</li>
<li>World Health Organization. (2023). <em>Global status report on road safety 2023</em>. Geneva: WHO.</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>