{
  "hash": "0d371d94df15b59ca1d9cb8a42549600",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take-home Exercise 1: Geospatial Analytics for Public Safety\"\nsubtitle: \"Network-constrained and Spatio-temporal Point Patterns of Road Traffic Accidents in the Bangkok Metropolitan Region, 2022\"\nauthor: \"Wang Xiaohan\"\ndate: \"2026-09-23\"\ndate-modified: \"last-modified\"\nformat:\n  html:\n    toc: true\nexecute:\n  eval: true\n  echo: true\n  message: false\n  warning: false\n  freeze: true\n---\n\n[View the Executive Summary (slides) →](Take-home_Ex01_summary.qmd){.btn .btn-light .btn-lg}\n\n# 1. Introduction\n\nRoad traffic crashes are a major public-safety problem in Thailand. WHO estimates about 18,218 road deaths in 2021, a rate of 25.4 per 100,000 population and one of the highest in Asia, with motorcyclists accounting for most deaths. The Bangkok Metropolitan Region (BMR), comprising Bangkok and five vicinity provinces, is the country's largest urban area, where crash patterns are likely to vary strongly across space and time. However, a concentration of crashes does not necessarily mean higher risk, as it may also reflect traffic volume, road density or how crashes are recorded.\n\nRoad accidents can only happen on roads, so this study treats them as events on a road network. Following the Network Constrained Spatial Point Patterns Analysis (NetSPAA) approach, the main analysis uses network kernel density estimation (NKDE) for first-order properties and network K- and G-functions for second-order properties. Planar and spatio-temporal methods from earlier exercises are used to describe temporal variation and to compare planar and network results.\n\n## 1.1 Research questions\n\n1.  Where and when are road traffic accidents in BMR concentrated in 2022? (first-order)\n2.  Are accidents clustered, regular or approximately random along the road network, compared with complete spatial randomness on the network? (second-order)\n3.  Do conclusions change between planar and network-constrained views, and between bandwidths? (comparison and value-added)\n\n# 2. Getting Started\n\nThe four packages used in the network-constrained analysis are loaded first, followed by the packages used for planar and spatio-temporal analysis. A fixed random seed makes all Monte Carlo simulations reproducible.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sf, spNetwork, tmap, tidyverse,\n               spatstat, sparr, stpp, terra)\nset.seed(1234)\n```\n:::\n\n\n\n| Package | Purpose |\n|----|----|\n| sf | import, wrangle and transform geospatial data |\n| spNetwork | lixels, network KDE, network K- and G-functions |\n| tmap | thematic mapping |\n| tidyverse | data wrangling, dates (`month()`, `yday()`) and statistical graphics |\n| spatstat | ppp/owin objects, planar KDE, Clark-Evans test, G/L functions, envelopes |\n| sparr | spatio-temporal KDE |\n| stpp | spatio-temporal K-function |\n| terra | convert planar KDE output to a raster for tmap |\n\n\n# 3. The Data\n\n| Dataset | Source | Format | Accessed | Coverage |\n|----|----|----|----|----|\n| Thailand Road Accident \\[2019-2022\\] | Kaggle (Thaweewat R.) | CSV | 2026-09-23 | Thailand, 2019-2022 (2022 used) |\n| Thailand ADM1 boundaries | geoBoundaries | Shapefile | 2026-09-23 | Thailand provinces |\n| OpenStreetMap roads | Geofabrik (extract 2026-09-21) | Shapefile | 2026-09-22 | Thailand |\n\n## 3.1 Study area: Bangkok Metropolitan Region (BMR)\n\nBMR is operationalised as Bangkok plus its five vicinity provinces, taken from the full-resolution geoBoundaries ADM1 layer (not the simplified version, to avoid wrongly dropping accidents near provincial borders and the coastline). The province names are checked first, because five of the six end with \" Province\".\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(st_read(dsn = \"data/geospatial\",\n              layer = \"geoBoundaries-THA-ADM1\",\n              quiet = TRUE)$shapeName)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n           Amnat Charoen Province                Ang Thong Province \n                                1                                 1 \n                          Bangkok                Bueng Kan Province \n                                1                                 1 \n                Buri Ram Province             Chachoengsao Province \n                                1                                 1 \n                Chai Nat Province               Chaiyaphum Province \n                                1                                 1 \n             Chanthaburi Province               Chiang Mai Province \n                                1                                 1 \n              Chiang Rai Province                Chon Buri Province \n                                1                                 1 \n                Chumphon Province                           Kalasin \n                                1                                 1 \n          Kamphaeng Phet Province             Kanchanaburi Province \n                                1                                 1 \n               Khon Kaen Province                    Krabi Province \n                                1                                 1 \n                 Lampang Province                  Lamphun Province \n                                1                                 1 \n                    Loei Province                  Lopburi Province \n                                1                                 1 \n            Mae Hong Son Province            Maha Sarakham Province \n                                1                                 1 \n                Mukdahan Province             Nakhon Nayok Province \n                                1                                 1 \n           Nakhon Pathom Province            Nakhon Phanom Province \n                                1                                 1 \n       Nakhon Ratchasima Province             Nakhon Sawan Province \n                                1                                 1 \n     Nakhon Si Thammarat Province                      Nan Province \n                                1                                 1 \n              Narathiwat Province         Nong Bua Lam Phu Province \n                                1                                 1 \n               Nong Khai Province               Nonthaburi Province \n                                1                                 1 \n            Pathum Thani Province                  Pattani Province \n                                1                                 1 \n                Phangnga Province              Phatthalung Province \n                                1                                 1 \n                  Phayao Province               Phetchabun Province \n                                1                                 1 \n             Phetchaburi Province                  Phichit Province \n                                1                                 1 \n             Phitsanulok Province Phra Nakhon Si Ayutthaya Province \n                                1                                 1 \n                   Phrae Province                   Phuket Province \n                                1                                 1 \n            Prachin Buri Province      Prachuap Khiri Khan Province \n                                1                                 1 \n                  Ranong Province               Ratchaburi Province \n                                1                                 1 \n                  Rayong Province                   Roi Et Province \n                                1                                 1 \n                 Sa Kaeo Province             Sakon Nakhon Province \n                                1                                 1 \n            Samut Prakan Province             Samut Sakhon Province \n                                1                                 1 \n         Samut Songkhram Province                 Saraburi Province \n                                1                                 1 \n                   Satun Province                Si Sa Ket Province \n                                1                                 1 \n               Sing Buri Province                 Songkhla Province \n                                1                                 1 \n               Sukhothai Province              Suphan Buri Province \n                                1                                 1 \n             Surat Thani Province                    Surin Province \n                                1                                 1 \n                     Tak Province                    Trang Province \n                                1                                 1 \n                    Trat Province         Ubon Ratchathani Province \n                                1                                 1 \n              Udon Thani Province              Uthai Thani Province \n                                1                                 1 \n               Uttaradit Province                     Yala Province \n                                1                                 1 \n                Yasothon Province \n                                1 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbmr_names <- c(\"Bangkok\", \"Nonthaburi Province\", \"Nakhon Pathom Province\",\n               \"Pathum Thani Province\", \"Samut Prakan Province\",\n               \"Samut Sakhon Province\")\n\nbmr_sf <- st_read(dsn = \"data/geospatial\",\n                  layer = \"geoBoundaries-THA-ADM1\") %>%\n  filter(shapeName %in% bmr_names) %>%\n  st_transform(crs = 32647)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `geoBoundaries-THA-ADM1' from data source \n  `/Users/wangxiaohan/ISSS626-GAA/Take-home_Ex/Take-home_Ex01/data/geospatial' \n  using driver `ESRI Shapefile'\nSimple feature collection with 77 features and 5 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 97.34381 ymin: 5.612851 xmax: 105.6368 ymax: 20.46483\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\nThe output should show 6 provinces in WGS 84 / UTM zone 47N (EPSG:32647). `st_is_valid()` checks that no polygon geometry is invalid.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnrow(bmr_sf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 6\n```\n\n\n:::\n\n```{.r .cell-code}\nst_crs(bmr_sf)$epsg\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 32647\n```\n\n\n:::\n\n```{.r .cell-code}\nany(!st_is_valid(bmr_sf))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbmr_union <- st_union(bmr_sf)\n```\n:::\n\n\n## 3.2 Road accident data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacc_raw <- read_csv(\"data/aspatial/thai_road_accident_2019_2022.csv\",\n                    show_col_types = FALSE)\nglimpse(acc_raw)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 81,735\nColumns: 18\n$ acc_code                    <dbl> 571905, 3790870, 599075, 571924, 599523, 5…\n$ incident_datetime           <dttm> 2019-01-01 00:00:00, 2019-01-01 00:03:00,…\n$ report_datetime             <dttm> 2019-01-02 06:11:00, 2020-02-20 13:48:00,…\n$ province_th                 <chr> \"ลพบุรี\", \"อุบลราชธานี\", \"ประจวบคีรีขันธ์\", \"เชียงใ…\n$ province_en                 <chr> \"Loburi\", \"Ubon Ratchathani\", \"Prachuap Kh…\n$ agency                      <chr> \"department of rural roads\", \"department o…\n$ route                       <chr> \"แยกทางหลวงหมายเลข 21 (กม.ที่ 31+000) - บ้านวั…\n$ vehicle_type                <chr> \"motorcycle\", \"private/passenger car\", \"mo…\n$ presumed_cause              <chr> \"driving under the influence of alcohol\", …\n$ accident_type               <chr> \"other\", \"rollover/fallen on straight road…\n$ number_of_vehicles_involved <dbl> 1, 1, 2, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, …\n$ number_of_fatalities        <dbl> 0, 0, 1, 0, 0, 0, 0, 1, 3, 0, 0, 1, 0, 0, …\n$ number_of_injuries          <dbl> 2, 2, 0, 1, 0, 2, 2, 0, 0, 1, 1, 0, 1, 1, …\n$ weather_condition           <chr> \"clear\", \"clear\", \"clear\", \"clear\", \"clear…\n$ latitude                    <dbl> 14.959105, 15.210738, 12.374259, 18.601721…\n$ longitude                   <dbl> 100.87346, 104.86269, 99.90795, 98.80420, …\n$ road_description            <chr> \"straight road\", \"straight road\", \"wide cu…\n$ slope_description           <chr> \"no slope\", \"no slope\", \"slope area\", \"no …\n```\n\n\n:::\n:::\n\n\n`incident_datetime` is already parsed as a date-time (`<dttm>`), and `latitude` and `longitude` are numeric.\n\n## 3.3 Road network data\n\nFollowing the NetSPAA workflow, the road network is imported as a line feature layer. Only roads intersecting BMR are read, because the full Thailand layer is over 600 MB; the spatial filter is converted to EPSG:4326 to match the OSM file. Only major road classes are kept, because all accidents in the dataset are recorded by national road agencies (Section 5.7), which manage these roads.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbmr_wkt <- bmr_union %>%\n  st_transform(crs = 4326) %>%\n  st_as_text()\n\nmajor_roads <- c(\"motorway\", \"motorway_link\", \"trunk\", \"trunk_link\",\n                 \"primary\", \"primary_link\", \"secondary\", \"secondary_link\",\n                 \"tertiary\", \"tertiary_link\")\n\nnetwork <- st_read(dsn = \"data/geospatial\",\n                   layer = \"gis_osm_roads_free_1\",\n                   wkt_filter = bmr_wkt) %>%\n  filter(fclass %in% major_roads) %>%\n  select(osm_id, fclass, name) %>%\n  st_transform(crs = 32647)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `gis_osm_roads_free_1' from data source \n  `/Users/wangxiaohan/ISSS626-GAA/Take-home_Ex/Take-home_Ex01/data/geospatial' \n  using driver `ESRI Shapefile'\nSimple feature collection with 621938 features and 10 fields\nGeometry type: LINESTRING\nDimension:     XY\nBounding box:  xmin: 99.76608 ymin: 13.43053 xmax: 101.0062 ymax: 14.32775\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\nspNetwork expects both layers to carry complete CRS information, so the CRS and the road classes kept are checked.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nst_crs(network)$epsg\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 32647\n```\n\n\n:::\n\n```{.r .cell-code}\ntable(network$fclass)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n      motorway  motorway_link        primary   primary_link      secondary \n          1268           1720           6273           2452           7339 \nsecondary_link       tertiary  tertiary_link          trunk     trunk_link \n          2073           5725            425           1464            668 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndir.create(\"data/rds\", recursive = TRUE, showWarnings = FALSE)\nwrite_rds(network, \"data/rds/network.rds\")\n```\n:::\n\n\n\n# 4. Study Design\n\n## 4.1 Point event definition\n\nA point event is one recorded road traffic accident (one unique `acc_code`) that occurred between 1 January and 31 December 2022, located by its reported longitude and latitude, and falling inside BMR. For the network analysis, events must also lie within 100 m of a major road, and are snapped to the network by spNetwork. Events are treated as an unmarked point pattern: attributes such as fatalities or vehicle type are not used as weights.\n\n| Issue | Handling | Section |\n|----|----|----|\n| Duplicate records | Removed by unique `acc_code` | 5.3 |\n| Repeated locations | Kept, counted with `duplicated()` and discussed | 5.9 |\n| Missing coordinates | Removed | 5.2 |\n| Swapped lat/long | Checked and corrected | 5.2 |\n| Coordinates outside Thailand | Removed | 5.2 |\n| Outside BMR | Removed with `st_intersects()` | 5.4 |\n| Outside 2022 | Removed | 5.1 |\n| More than 100 m from a major road | Excluded from the network analysis | 5.10 |\n\n## 4.2 Spatial and temporal study window\n\n| Item | Decision | Justification |\n|----|----|----|\n| Spatial window | Union of 6 BMR provinces (planar); major road network within BMR (network) | Operationalises \"Bangkok Greater Metropolitan Area\" with official provincial boundaries; the network is the space where accidents can occur |\n| Temporal window | 1 Jan - 31 Dec 2022 | Required by the brief for the 2019-2022 dataset |\n| Temporal unit | Month (STKDE, 6.5); day of year (STKDE, 6.6; space-time K-function, 7.3; daily graphic, 6.1) | Months give enough events per slice; day of year allows data-driven temporal bandwidths and shows holiday peaks |\n\n## 4.3 Methodological decisions\n\n| Decision | Choice | Justification |\n|----|----|----|\n| CRS | WGS 84 / UTM 47N (EPSG:32647) | Metric units for bandwidth and distance; zone 47N covers Bangkok |\n| Network | OSM major roads (motorway to tertiary, with links) | Matches the agencies that recorded the accidents |\n| Lixels | 500 m, minimum 250 m | About half the NKDE bandwidth, giving detail without too many lixels |\n| NKDE | Quartic kernel, simple method, bandwidth 1 km (sensitivity: 0.5 and 2 km) | Quartic and simple follow the NetSPAA workflow; 1 km covers junction-to-corridor scale |\n| Network K/G-functions | 0-5 km, step 100 m, width 200 m, 50 simulations, Bangkok only | Range covers local to corridor scale; Bangkok only for computation time |\n| Planar KDE | Gaussian kernel; bw.diggle, bw.ppl, bw.scott, fixed 0.5-5 km, adaptive compared | Used for comparison with the network view |\n| Planar edge correction | Border (default for large patterns) | Fast for thousands of points |\n| Planar simulations | 99 | Global envelopes with rank 1 give α = 0.01 |\n| Null models | CSR on the network (binomial process on the network); planar CSR for comparison | Network CSR accounts for the fact that accidents can only occur on roads |\n\n## 4.4 Analytical assumptions\n\n| Method | Key assumption | Reasonable here? |\n|----|----|----|\n| NKDE | Accidents occur on the network, and network distance is the relevant distance | Yes for accidents within 100 m of a major road; not for accidents on minor roads, which are excluded |\n| Network K/G vs network CSR | Accidents are equally likely anywhere on the network | Partly: traffic volume varies strongly between roads, so clustering may reflect exposure rather than interaction |\n| Planar KDE | Accidents can occur anywhere in the window | No: planar KDE spreads intensity into areas without roads |\n| Planar G/L vs CSR | Constant intensity across BMR | No: intensity clearly varies, so clustering under planar CSR may just reflect uneven intensity |\n| STKDE | Spatial pattern changes smoothly over time | Reasonable for seasonal change, but short holiday peaks are smoothed out |\n| Space-time K-function | Constant intensity in space and time | No: like planar CSR, it cannot separate interaction from uneven intensity |\n| All methods | Recorded accidents represent all accidents | No: data come from national road agencies, so city streets are likely under-recorded |\n\n\n# 5. Data Wrangling and Quality Assessment\n\n## 5.1 Temporal filtering and derived time fields\n\nRecords are kept if they occurred in 2022. The boundaries are written as seconds since 1 January 1970 (UTC), because `incident_datetime` is stored in UTC: 1640995200 is 2022-01-01 00:00 and 1672531200 is 2023-01-01 00:00.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(is.na(acc_raw$incident_datetime))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacc_2022 <- acc_raw %>%\n  filter(as.numeric(incident_datetime) >= 1640995200,\n         as.numeric(incident_datetime) < 1672531200) %>%\n  mutate(DayofYear = yday(incident_datetime)) %>%\n  mutate(Month_num = month(incident_datetime)) %>%\n  mutate(Month_fac = month(incident_datetime,\n                           label = TRUE,\n                           abbr = FALSE))\nnrow(acc_2022)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 21032\n```\n\n\n:::\n:::\n\n\n## 5.2 Missing, swapped and invalid coordinates\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(is.na(acc_2022$latitude) | is.na(acc_2022$longitude))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 189\n```\n\n\n:::\n:::\n\n\nRecords whose latitude and longitude appear to be swapped (latitude in Thailand's longitude range and vice versa) are corrected rather than dropped.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacc_fixed <- acc_2022 %>%\n  mutate(swapped = latitude >= 97 & latitude <= 106 &\n                   longitude >= 5 & longitude <= 21) %>%\n  mutate(latitude_fix = ifelse(swapped, longitude, latitude),\n         longitude_fix = ifelse(swapped, latitude, longitude))\n\nsum(acc_fixed$swapped, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacc_valid <- acc_fixed %>%\n  filter(!is.na(latitude_fix), !is.na(longitude_fix)) %>%\n  filter(longitude_fix >= 97, longitude_fix <= 106,\n         latitude_fix >= 5, latitude_fix <= 21)\n```\n:::\n\n\n## 5.3 Duplicate records\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(duplicated(acc_valid$acc_code))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\nacc_dedup <- acc_valid %>%\n  filter(!duplicated(acc_code))\n```\n:::\n\n\n## 5.4 Creating sf object and spatial filtering\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacc_sf <- acc_dedup %>%\n  st_as_sf(coords = c(\"longitude_fix\", \"latitude_fix\"),\n           crs = 4326) %>%\n  st_transform(crs = 32647)\n\nacc_bmr_sf <- acc_sf %>%\n  filter(lengths(st_intersects(acc_sf, bmr_union)) > 0)\n```\n:::\n\n\n## 5.5 Location consistency check\n\nEach point is joined to the province it falls in and compared with the province recorded in the data. `distinct()` removes duplicate rows created by points lying exactly on a provincial border.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata.frame(\n  step = c(\"Raw (2019-2022)\", \"Year 2022\", \"Valid coordinates\",\n           \"After de-duplication\", \"Inside BMR\"),\n  n = c(nrow(acc_raw), nrow(acc_2022), nrow(acc_valid),\n        nrow(acc_dedup), nrow(acc_bmr_sf))\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  step     n\n1      Raw (2019-2022) 81735\n2            Year 2022 21032\n3    Valid coordinates 20843\n4 After de-duplication 20843\n5           Inside BMR  3599\n```\n\n\n:::\n:::\n\n\nOf the 81,735 records, 21,032 occurred in 2022. All dates were parsed successfully. 189 records lacked coordinates and were removed; no swapped or out-of-Thailand coordinates and no duplicate `acc_code` values were found. 3,599 accidents fall inside BMR.\n\n## 5.6 Accidents by province\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(acc_bmr_sf$province_en)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n                 Bangkok             Kanchanaburi            Nakhon Pathom \n                    1801                        4                      134 \n              Nonthaburi             Pathum Thani Phra Nakhon Si Ayutthaya \n                     175                      486                        4 \n            Samut Prakan             Samut Sakhon                  unknown \n                     669                      324                        2 \n```\n\n\n:::\n:::\n\n\n## 5.7 Observation process\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(acc_bmr_sf$agency)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n          department of highways        department of rural roads \n                            2883                              246 \nexpressway authority of thailand \n                             470 \n```\n\n\n:::\n:::\n\n\n::: {.callout-note title=\"Interpretation\"}\nAll 3,599 BMR accidents were reported by national road agencies: the Department of Highways (80.1%), the Expressway Authority of Thailand (13.1%) and the Department of Rural Roads (6.8%). None come from the Bangkok Metropolitan Administration, which manages most local streets in Bangkok. Accidents on these streets are therefore likely under-represented, and concentrations in the following analysis should be read as patterns of recorded accidents on highways, expressways and rural roads, not of all accidents in BMR.\n:::\n\n## 5.8 Mapping the geospatial data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(bmr_sf) +\n  tm_polygons(fill = \"grey95\") +\n  tm_text(\"shapeName\", size = 0.7) +\ntm_shape(acc_bmr_sf) +\n  tm_dots(size = 0.1, fill = \"red\") +\ntm_title(\"Road accidents in BMR, 2022\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\n::: {.callout-note title=\"Interpretation\"}\nThe 3,599 recorded accidents are not spread evenly across BMR but align along linear corridors radiating from Bangkok towards Pathum Thani, Samut Prakan and Samut Sakhon, with sparser points in Nakhon Pathom. Inner Bangkok shows relatively few accidents despite its density, consistent with the absence of BMA-managed streets from the data (Section 5.7). This visual concentration does not yet indicate clustering or higher risk: it must be assessed against a reference model (Section 7), and the linear pattern suggests that the road network itself shapes where accidents can occur.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(bmr_sf) +\n  tm_polygons(fill = \"grey95\") +\ntm_shape(acc_bmr_sf) +\n  tm_dots(size = 0.1, fill = \"red\") +\ntm_facets(by = \"Month_fac\",\n          free.coords = FALSE)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-21-1.png){width=1152}\n:::\n:::\n\n\n::: {.callout-note title=\"Interpretation\"}\nFaceting by month shows that accidents occur along the same major corridors throughout 2022, suggesting that the spatial structure of recorded accidents is largely stable over time rather than shifting between areas. Differences in the number of points between months are difficult to judge visually from dot maps; monthly counts (Section 6.1) and spatio-temporal KDE (Sections 6.5 and 6.6) are used to assess temporal variation in intensity more rigorously.\n:::\n\n## 5.9 Converting to spatstat objects\n\nFor the planar and spatio-temporal methods, the accidents are converted to a ppp object and combined with an owin object of BMR. `st_geometry()` keeps only the point locations, so the ppp object carries no marks.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacc_ppp <- as.ppp(st_geometry(acc_bmr_sf))\nsummary(acc_ppp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPlanar point pattern:  3599 points\nAverage intensity 3.326903e-07 points per square unit\n\n*Pattern contains duplicated points*\n\nCoordinates are given to 10 decimal places\n\nWindow: rectangle = [587647.2, 709360] x [1487640.2, 1576520.5] units\n                    (121700 x 88880 units)\nWindow area = 10817900000 square units\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nany(duplicated(acc_ppp))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(duplicated(acc_ppp))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 321\n```\n\n\n:::\n:::\n\n\nSome accidents share their exact location with another accident. These may be repeated accidents at the same site, or locations recorded at fixed reference points such as kilometre markers. They are kept, because removing them would discard real accidents; the effect on the planar G-function is discussed in Section 7.2.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbmr_owin <- as.owin(bmr_union)\nplot(bmr_owin)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\naccBMR_ppp <- acc_ppp[bmr_owin]\naccBMR_ppp.km <- rescale.ppp(accBMR_ppp, 1000, \"km\")\nplot(accBMR_ppp.km)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\n## 5.10 Preparing events for the network analysis\n\nspNetwork snaps each event to its nearest road segment. To avoid snapping accidents that lie far from any major road, accidents are kept only if they fall within a 100 m buffer of the major road network.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nroad_buffer <- st_buffer(network, dist = 100)\n\nacc_bmr_sf <- acc_bmr_sf %>%\n  mutate(near_road = lengths(st_intersects(acc_bmr_sf, road_buffer)) > 0)\n\ntable(acc_bmr_sf$near_road)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nFALSE  TRUE \n    5  3594 \n```\n\n\n:::\n\n```{.r .cell-code}\nacc_net <- acc_bmr_sf %>%\n  filter(near_road)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(acc_bmr_sf, \"data/rds/acc_bmr_sf.rds\")\nwrite_rds(acc_net, \"data/rds/acc_net.rds\")\n```\n:::\n\n\nBefore the analysis, the network and the events are plotted together, as in the NetSPAA workflow.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(st_geometry(network))\nplot(st_geometry(acc_net), add = T, col = 'red', pch = 19, cex = 0.3)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-28-1.png){width=960}\n:::\n:::\n\n\n::: {.callout-note title=\"Interpretation\"}\nAlmost all accidents (3,594 of 3,599) lie within 100 m of a major road, which supports treating accidents as events on the major road network. The five excluded accidents are likely on minor roads or mislocated. The plot shows that accidents follow a small number of major roads, while much of the network carries few or no recorded accidents.\n:::\n\n# 6. First-order Point Patterns Analysis\n\n## 6.1 Temporal variation\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(acc_bmr_sf, aes(x = Month_num)) +\n  geom_histogram(binwidth = 1) +\n  labs(x = \"Month (1 = January)\", y = \"No. of accidents\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n\nThe red dashed lines mark the end of the New Year campaign (4 January, day 4), the Songkran \"seven dangerous days\" (11-17 April, days 101-107) and the start of the next New Year campaign (29 December, day 363).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(acc_bmr_sf, aes(x = DayofYear)) +\n  geom_histogram(binwidth = 1) +\n  geom_vline(xintercept = c(4, 101, 107, 363),\n             linetype = \"dashed\", colour = \"red\") +\n  labs(x = \"Day of year, 2022\", y = \"No. of accidents per day\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\n::: {.callout-note title=\"Interpretation\"}\nRecorded accidents vary over time at two scales. Monthly counts range from about 210 in February to about 395 in October, with generally higher counts in the second half of 2022. Daily counts usually fall between 5 and 15, but the most prominent peaks coincide with the New Year and Songkran campaign periods, reaching about 36 accidents at the end of December. These peaks coincide with holiday travel periods, but the data alone cannot show why they occur. Counts are not adjusted for traffic volume, cover only recorded accidents on national roads, and come from a single year, so peaks indicate more recorded accidents rather than necessarily higher risk.\n:::\n\n## 6.2 Intensity by province\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbmr_sf <- bmr_sf %>%\n  mutate(n_acc = lengths(st_intersects(bmr_sf, acc_bmr_sf))) %>%\n  mutate(area_km2 = as.numeric(st_area(bmr_sf)) / 1000000) %>%\n  mutate(acc_per_km2 = n_acc / area_km2)\n\nbmr_sf %>%\n  select(shapeName, n_acc, area_km2, acc_per_km2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 6 features and 4 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 587130.4 ymin: 1484749 xmax: 712441.7 ymax: 1579087\nProjected CRS: WGS 84 / UTM zone 47N\n               shapeName n_acc  area_km2 acc_per_km2\n1                Bangkok  1802 1570.7019  1.14725779\n2 Nakhon Pathom Province   138 2088.4542  0.06607758\n3    Nonthaburi Province   174  638.9550  0.27231964\n4  Pathum Thani Province   491 1513.6408  0.32438344\n5  Samut Sakhon Province   323  839.4175  0.38479063\n6  Samut Prakan Province   671  952.9092  0.70415941\n                        geometry\n1 MULTIPOLYGON (((706791.8 15...\n2 MULTIPOLYGON (((643530.5 15...\n3 MULTIPOLYGON (((669340.7 15...\n4 MULTIPOLYGON (((706784.4 15...\n5 MULTIPOLYGON (((644134.6 15...\n6 MULTIPOLYGON (((701236.5 15...\n```\n\n\n:::\n:::\n\n\n## 6.3 Network KDE (NKDE)\n\n### 6.3.1 Preparing the lixels objects\n\nBefore computing NKDE, the network is cut into lixels. The lixel length is set to 500 m and the minimum length to 250 m, about half of the 1 km bandwidth.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlixels <- lixelize_lines(network,\n                         500,\n                         mindist = 250)\n```\n:::\n\n\n### 6.3.2 Generating line centre points\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsamples <- lines_center(lixels)\n```\n:::\n\n\n### 6.3.3 Performing NKDE\n\nThe quartic kernel and the simple method are used, as in the NetSPAA workflow. The bandwidth is 1 km, measured along the network. `grid_shape = c(3, 3)` splits the large BMR network into a 3 x 3 grid so that the calculation fits in memory; it does not change the result.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndensities <- nkde(network,\n                  events = acc_net,\n                  w = rep(1, nrow(acc_net)),\n                  samples = samples,\n                  kernel_name = \"quartic\",\n                  bw = 1000,\n                  div = \"bw\",\n                  method = \"simple\",\n                  digits = 1,\n                  tol = 1,\n                  grid_shape = c(3, 3),\n                  max_depth = 8,\n                  agg = 5,\n                  sparse = TRUE,\n                  verbose = FALSE)\n```\n:::\n\n\n### 6.3.4 Visualising NKDE\n\nThe density values are inserted into `samples` and `lixels`, then rescaled from events per metre to events per kilometre.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsamples$density <- densities\nlixels$density <- densities\n\nsamples$density <- samples$density * 1000\nlixels$density <- lixels$density * 1000\n\nwrite_rds(lixels, \"data/rds/lixels.rds\")\n```\n:::\n\n\nA static map is used instead of the interactive `tmap_mode('view')`, because drawing about 60,000 lixels interactively would make the HTML page very large. Road segments with zero density are drawn in grey, so that the coloured segments show where recorded accidents concentrate. Quantile classes are used because most segments have very low values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlixels_pos <- lixels %>%\n  filter(density > 0)\n\ntm_shape(bmr_sf) +\n  tm_polygons(fill = \"grey95\") +\ntm_shape(network) +\n  tm_lines(col = \"grey80\") +\ntm_shape(lixels_pos) +\n  tm_lines(col = \"density\",\n           col.scale = tm_scale_intervals(style = \"quantile\",\n                                          values = \"viridis\"),\n           col.legend = tm_legend(title = \"NKDE (events per km)\"),\n           lwd = 2) +\ntm_title(\"Network KDE of road accidents, BMR 2022\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-36-1.png){width=960}\n:::\n:::\n\n\n::: {.callout-note title=\"Interpretation\"}\nNKDE (quartic kernel, 1 km bandwidth measured along the network) estimates accident density on each road segment rather than across continuous space. Density is concentrated on a small number of specific roads: a north–south corridor through eastern Bangkok into Pathum Thani, roads across southern Bangkok into Samut Prakan, where the highest values occur, and a south-western corridor towards Samut Sakhon. Most of the major road network, including much of inner Bangkok, shows zero or near-zero density. Because density is calculated along roads, it identifies particular road segments rather than broad areas, which is more directly useful for targeting interventions. It reflects only accidents recorded by national road agencies, and is not adjusted for traffic volume, so high density does not necessarily mean higher risk.\n:::\n\n## 6.4 Planar KDE for comparison\n\nPlanar KDE is computed to compare the network view with the conventional view, in which accidents can occur anywhere in the window.\n\n### 6.4.1 Automatic bandwidth selection\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbw.diggle(accBMR_ppp.km)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     sigma \n0.02307687 \n```\n\n\n:::\n\n```{.r .cell-code}\nbw.ppl(accBMR_ppp.km)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    sigma \n0.7507077 \n```\n\n\n:::\n\n```{.r .cell-code}\nbw.scott(accBMR_ppp.km)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n sigma.x  sigma.y \n5.238214 4.082151 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkde_accBMR.bw <- density(accBMR_ppp.km,\n                         sigma = bw.diggle,\n                         edge = TRUE,\n                         kernel = \"gaussian\")\nkde_accBMR.ppl <- density(accBMR_ppp.km,\n                          sigma = bw.ppl,\n                          edge = TRUE,\n                          kernel = \"gaussian\")\nkde_accBMR.scott <- density(accBMR_ppp.km,\n                            sigma = bw.scott,\n                            edge = TRUE,\n                            kernel = \"gaussian\")\npar(mfrow = c(1, 3))\nplot(kde_accBMR.bw, main = \"bw.diggle\")\nplot(kde_accBMR.ppl, main = \"bw.ppl\")\nplot(kde_accBMR.scott, main = \"bw.scott\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-38-1.png){width=1344}\n:::\n:::\n\n\n### 6.4.2 Bandwidth sensitivity\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(2, 2))\nfor (s in c(0.5, 1, 2, 5)) {\n  plot(density(accBMR_ppp.km,\n               sigma = s,\n               edge = TRUE,\n               kernel = \"gaussian\"),\n       main = paste(\"sigma =\", s, \"km\"))\n}\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-39-1.png){width=960}\n:::\n:::\n\n\n### 6.4.3 Fixed vs adaptive bandwidth\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkde_accBMR_adaptive <- adaptive.density(accBMR_ppp.km,\n                                        method = \"kernel\")\npar(mfrow = c(1, 2))\nplot(kde_accBMR.ppl, main = \"Fixed bandwidth (bw.ppl)\")\nplot(kde_accBMR_adaptive, main = \"Adaptive bandwidth\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-40-1.png){width=1152}\n:::\n:::\n\n\n### 6.4.4 Mapping the selected planar KDE\n\nbw.ppl (0.79 km) is selected. bw.diggle (0.09 km) and the adaptive KDE produce very spiky surfaces dominated by a few sharp peaks, while bw.scott (about 5.2 km x 4.1 km) and the 5 km bandwidth merge the corridors into one broad hotspot. The sensitivity plots show that bandwidths of about 0.5-1 km preserve the corridor structure. For mapping, the KDE is computed on the metre-based ppp object, so that the raster coordinates match EPSG:32647.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkde_accBMR_m <- density(accBMR_ppp,\n                        sigma = bw.ppl,\n                        edge = TRUE,\n                        kernel = \"gaussian\")\n\nkde_accBMR_terra <- rast(kde_accBMR_m)\ncrs(kde_accBMR_terra) <- \"EPSG:32647\"\nkde_accBMR_terra\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nclass       : SpatRaster\nsize        : 128, 128, 1  (nrow, ncol, nlyr)\nresolution  : 978.9945, 737.0174  (x, y)\nextent      : 587130.4, 712441.7, 1484749, 1579087  (xmin, xmax, ymin, ymax)\ncoord. ref. : WGS 84 / UTM zone 47N (EPSG:32647)\nsource(s)   : memory\nname        :    lyr.1\nmin value   :       -0\nmax value   : 0.000029\nunit        : unit\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(kde_accBMR_terra) +\n  tm_raster(col.scale = tm_scale_continuous(values = \"viridis\"),\n            col.legend = tm_legend(title = \"Density values\")) +\ntm_shape(bmr_sf) +\n  tm_borders(col = \"grey40\") +\ntm_title(\"Planar KDE of road accidents, BMR 2022\") +\n  tm_graticules(labels.size = 0.7) +\n  tm_compass()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-42-1.png){width=672}\n:::\n:::\n\n\n::: {.callout-note title=\"Interpretation\"}\nUsing the bw.ppl bandwidth (0.79 km), the planar KDE shows the same corridors as the NKDE: a north–south corridor through Bangkok into Pathum Thani, an east–west corridor across southern Bangkok into Samut Prakan, and a south-western corridor towards Samut Sakhon, with the highest intensity in southern Bangkok near the Samut Prakan boundary. The location of these hotspots is stable across bandwidths of 0.5-2 km. However, planar KDE spreads intensity into areas without roads, such as fields and rivers, and cannot show which particular road carries the accidents. Comparing it with Section 6.3 shows that the network view gives the same broad picture but locates it on specific road segments.\n:::\n\n## 6.5 Spatio-temporal KDE by month\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacc_month <- acc_bmr_sf %>%\n  select(Month_num)\nacc_month_ppp <- as.ppp(acc_month)\nacc_month_owin <- acc_month_ppp[bmr_owin]\nsummary(acc_month_owin)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMarked planar point pattern:  3599 points\nAverage intensity 4.732986e-07 points per square unit\n\n*Pattern contains duplicated points*\n\nCoordinates are given to 10 decimal places\n\nmarks are numeric, of type 'double'\nSummary:\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  1.000   4.000   7.000   6.994  10.000  12.000 \n\nWindow: polygonal boundary\nsingle connected closed polygon with 1699 vertices\nenclosing rectangle: [587130.4, 712441.7] x [1484748.9, 1579087.2] units\n                     (125300 x 94340 units)\nWindow area = 7604080000 square units\nFraction of frame area: 0.643\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nst_kde <- spattemp.density(acc_month_owin)\nsummary(st_kde)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatiotemporal Kernel Density Estimate\n\nBandwidths\n  h = 4882.467 (spatial)\n  lambda = 0.0285 (temporal)\n\nNo. of observations\n  3599 \n\nSpatial bound\n  Type: polygonal\n  2D enclosure: [587130.4, 712441.7] x [1484749, 1579087]\n\nTemporal bound\n  [1, 12]\n\nEvaluation\n  128 x 128 x 12 trivariate lattice\n  Density range: [9.448582e-22, 2.845214e-09]\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntims <- c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)\npar(mfcol = c(3, 4))\nfor (i in tims) {\n  plot(st_kde, i,\n       override.par = FALSE,\n       fix.range = TRUE,\n       main = paste(\"KDE at month\", i))\n}\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-45-1.png){width=1152}\n:::\n:::\n\n\n::: {.callout-note title=\"Interpretation\"}\nThe spatio-temporal KDE shows that the location of the main accident hotspot, in south-eastern Bangkok near the Samut Prakan boundary, is stable throughout 2022, while its intensity varies by month. Intensity is highest in December and relatively high in January, and lowest in February, March, May and June, consistent with the monthly counts in Section 6.1. From around August, a secondary concentration towards Samut Sakhon also becomes more visible. The automatically selected spatial bandwidth (about 4.9 km) is large, so these maps show broad hotspots rather than individual road corridors. The temporal bandwidth is very small relative to the monthly time unit, so each panel mainly reflects that month's accidents. Monthly aggregation may also hide short peaks such as the Songkran week.\n:::\n\n## 6.6 Spatio-temporal KDE by day of year\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacc_yday_ppp <- acc_bmr_sf %>%\n  select(DayofYear) %>%\n  as.ppp()\nacc_yday_owin <- acc_yday_ppp[bmr_owin]\nsummary(acc_yday_owin)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMarked planar point pattern:  3599 points\nAverage intensity 4.732986e-07 points per square unit\n\n*Pattern contains duplicated points*\n\nCoordinates are given to 10 decimal places\n\nmarks are numeric, of type 'double'\nSummary:\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n    1.0   104.0   208.0   197.5   292.0   365.0 \n\nWindow: polygonal boundary\nsingle connected closed polygon with 1699 vertices\nenclosing rectangle: [587130.4, 712441.7] x [1484748.9, 1579087.2] units\n                     (125300 x 94340 units)\nWindow area = 7604080000 square units\nFraction of frame area: 0.643\n```\n\n\n:::\n:::\n\n\n`BOOT.spattemp()` selects the spatial and temporal bandwidths by bootstrap.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nBOOT.spattemp(acc_yday_owin)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nInitialising...Done.\nOptimising...\nh = 4882.467 \b; lambda = 23.86965 \nh = 5370.714 \b; lambda = 23.86965 \nh = 4882.467 \b; lambda = 512.1164 \nh = 5004.529 \b; lambda = 267.993 \nh = 5065.56 \b; lambda = 145.9313 \nh = 5096.075 \b; lambda = 84.90049 \nh = 4607.828 \b; lambda = 84.90049 \nh = 4226.386 \b; lambda = 115.4159 \nh = 4439.994 \b; lambda = 176.4468 \nh = 4771.849 \b; lambda = 62.01392 \nh = 3902.159 \b; lambda = 92.52934 \nh = 3305.201 \b; lambda = 96.34377 \nh = 2759.738 \b; lambda = 149.7458 \nh = 3262.766 \b; lambda = 127.8128 \nh = 2341.582 \b; lambda = 108.7407 \nh = 2812.783 \b; lambda = 110.4095 \nh = 2855.218 \b; lambda = 78.94045 \nh = 2651.444 \b; lambda = 54.50427 \nh = 3347.637 \b; lambda = 64.87474 \nh = 3213.923 \b; lambda = 76.25843 \nh = 2763.94 \b; lambda = 58.8551 \nh = 3169.886 \b; lambda = 86.9716 \nh = 2899.255 \b; lambda = 68.22727 \nh = 2966.913 \b; lambda = 72.91335 \nh = 2608.208 \b; lambda = 75.59537 \nh = 3062.495 \b; lambda = 76.09266 \nDone.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         h     lambda \n3062.49456   76.09266 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# TODO: check h and lambda against the BOOT.spattemp() output above;\n# they were 3061.77 and 76.07 in the earlier run, and may change slightly\nkde_yday <- spattemp.density(acc_yday_owin,\n                             h = 3062,\n                             lambda = 76)\nsummary(kde_yday)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatiotemporal Kernel Density Estimate\n\nBandwidths\n  h = 3062 (spatial)\n  lambda = 76 (temporal)\n\nNo. of observations\n  3599 \n\nSpatial bound\n  Type: polygonal\n  2D enclosure: [587130.4, 712441.7] x [1484749, 1579087]\n\nTemporal bound\n  [1, 365]\n\nEvaluation\n  128 x 128 x 365 trivariate lattice\n  Density range: [7.881223e-19, 5.140111e-12]\n```\n\n\n:::\n:::\n\n\nThe four days shown are mid-February, mid-April, mid-July and mid-October. Days near the start and end of the year are avoided because estimates there are affected by the temporal boundary.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntims <- c(46, 105, 196, 288)\npar(mfcol = c(2, 2))\nfor (i in tims) {\n  plot(kde_yday, i,\n       override.par = FALSE,\n       fix.range = TRUE,\n       main = paste(\"KDE at day\", i))\n}\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-49-1.png){width=1152}\n:::\n:::\n\n\n::: {.callout-note title=\"Interpretation\"}\nUsing day of year with bootstrap-selected bandwidths (h ≈ 3.1 km, lambda ≈ 76 days), the STKDE shows a stable core and a changing periphery. The main hotspot in south-eastern Bangkok near the Samut Prakan boundary, and the north–south corridor into Pathum Thani, persist throughout 2022. In contrast, the south-western corridor towards Samut Sakhon is faint in February and April but becomes increasingly prominent in July and October, when overall intensity is also higher, consistent with the monthly counts in Section 6.1. However, the 76-day temporal bandwidth pools accidents over roughly two to three months, so short-lived peaks such as the Songkran and New Year holidays are smoothed out; the daily graphic in Section 6.1 remains the evidence for those peaks.\n:::\n\n# 7. Second-order Point Patterns Analysis\n\n## 7.1 Network K- and G-function analysis\n\n**Research question:** after accounting for the fact that accidents can only occur on the road network, are accidents clustered, regular or approximately random along the network?\n\n**Hypotheses:**\n\nH0: The observed accidents are uniformly distributed over the major road network in Bangkok.\n\nH1: The observed accidents are not uniformly distributed over the major road network in Bangkok.\n\nThe CSR test is based on the binomial point process, which assumes accidents are randomly and independently distributed over the network. If H0 is rejected, accidents may be spatially interacting and dependent on each other, forming non-random patterns.\n\nThe analysis is restricted to Bangkok, because simulating random points on the full BMR network is very slow. `kfunctions()` computes both the network K-function and the network G-function, and compares them with 50 simulations of random points on the network.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbkk_sf <- bmr_sf %>%\n  filter(shapeName == \"Bangkok\")\n\nnetwork_bkk <- network %>%\n  filter(lengths(st_intersects(network, bkk_sf)) > 0)\n\nacc_bkk <- acc_net %>%\n  filter(lengths(st_intersects(acc_net, bkk_sf)) > 0)\n\nnrow(acc_bkk)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1801\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkfun_acc <- kfunctions(network_bkk,\n                       acc_bkk,\n                       start = 0,\n                       end = 5000,\n                       step = 100,\n                       width = 200,\n                       nsim = 50,\n                       resolution = 50,\n                       verbose = FALSE,\n                       conf_int = 0.05)\nwrite_rds(kfun_acc, \"data/rds/kfun_acc.rds\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkfun_acc <- read_rds(\"data/rds/kfun_acc.rds\")\n```\n:::\n\n\n\nThe blue line is the empirical network K-function and the grey envelope shows the 2.5%-97.5% interval of the 50 simulations. A blue line above the envelope indicates clustering at that distance, and below it indicates regularity.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkfun_acc$plotk\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-53-1.png){width=672}\n:::\n:::\n\n\nThe network G-function counts pairs of accidents within each 200 m ring, so it shows at which specific distances clustering or regularity occurs.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkfun_acc$plotg\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-54-1.png){width=672}\n:::\n:::\n\n\n::: {.callout-note title=\"Interpretation\"}\n<!-- TODO: write after running. State the distance ranges where the blue line is above, inside or below the envelope, for both the K- and G-functions. -->\n:::\n\n## 7.2 Planar tests against CSR, for comparison\n\nThese tests use planar CSR as the null model: accidents are assumed equally likely anywhere in BMR, including where there are no roads. They are included to show how much the conclusion depends on the null model.\n\nH0: accidents are randomly distributed in BMR (CSR). H1: accidents are clustered.\n\n### 7.2.1 Clark-Evans test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclarkevans.test(accBMR_ppp.km,\n                correction = \"none\",\n                clipregion = NULL,\n                alternative = c(\"clustered\"),\n                method = \"MonteCarlo\",\n                nsim = 99)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tClark-Evans test\n\tNo edge correction\n\tMonte Carlo test based on 99 simulations of CSR with fixed n\n\ndata:  accBMR_ppp.km\nR = 0.26518, p-value = 0.01\nalternative hypothesis: clustered (R < 1)\n```\n\n\n:::\n:::\n\n\n### 7.2.2 G-function\n\n\n::: {.cell}\n\n```{.r .cell-code}\nG_acc.csr <- envelope(accBMR_ppp.km, Gest, nsim = 99)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGenerating 99 simulated realisations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,\n41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,\n61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,\n81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, \n99.\n\nDone.\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(G_acc.csr, xlim = c(0, 2))\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-56-1.png){width=672}\n:::\n:::\n\n\n### 7.2.3 L-function\n\nWith 99 simulations and `rank = 1`, the global envelope corresponds to a significance level of 0.01.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nL_acc.csr <- envelope(accBMR_ppp.km, Lest, nsim = 99, rank = 1, glocal = TRUE)\nwrite_rds(L_acc.csr, \"data/rds/L_acc_csr.rds\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nL_acc.csr <- read_rds(\"data/rds/L_acc_csr.rds\")\nplot(L_acc.csr, . - r ~ r, xlab = \"d (km)\", ylab = \"L(d)-r\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-58-1.png){width=672}\n:::\n:::\n\n\n::: {.callout-note title=\"Interpretation\"}\nAgainst planar CSR, all tests indicate strong clustering: the Clark-Evans ratio is well below 1 (<!-- TODO: R value -->, p = 0.01), and the G- and L-functions lie far above their envelopes. The G-function also jumps at distance 0, because accidents sharing exact locations have a nearest-neighbour distance of zero. However, planar CSR assumes accidents can occur anywhere in BMR, whereas Sections 5.10 and 6.3 show they are confined to a small number of roads. Much of this apparent clustering therefore reflects the road network itself. This is why the network K-function in Section 7.1, which uses CSR on the network as the null model, is the main second-order test in this study.\n:::\n\n## 7.3 Spatio-temporal K-function\n\n**Research question:** do accidents that are close in space also tend to be close in time?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoords <- st_coordinates(acc_bmr_sf)\n\nacc_df <- data.frame(\n  x = coords[, 1],\n  y = coords[, 2],\n  t = acc_bmr_sf$DayofYear)\n\nacc_stpp <- as.3dpoints(acc_df)\nclass(acc_stpp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"stpp\"\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nacc_stik <- STIKhat(acc_stpp)\nplotK(acc_stik)\n```\n:::\n\n\n::: {.callout-note title=\"Interpretation\"}\n<!-- TODO: write after running. High contour values at small spatial (u) and temporal (v) distances suggest clustering in both space and time. Note that STIKhat assumes constant intensity, so it cannot separate interaction from uneven intensity. -->\n:::\n\n# 8. Value-added Analysis: Sensitivity of NKDE to Bandwidth\n\n**Research question:** are the high-density road segments identified in Section 6.3 robust to the choice of NKDE bandwidth?\n\nThe NKDE is recomputed with bandwidths of 500 m and 2 km, using the same lixels, samples and settings as Section 6.3.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndensities_500 <- nkde(network,\n                      events = acc_net,\n                      w = rep(1, nrow(acc_net)),\n                      samples = samples,\n                      kernel_name = \"quartic\",\n                      bw = 500,\n                      div = \"bw\",\n                      method = \"simple\",\n                      digits = 1,\n                      tol = 1,\n                      grid_shape = c(3, 3),\n                      max_depth = 8,\n                      agg = 5,\n                      sparse = TRUE,\n                      verbose = FALSE)\n\ndensities_2000 <- nkde(network,\n                       events = acc_net,\n                       w = rep(1, nrow(acc_net)),\n                       samples = samples,\n                       kernel_name = \"quartic\",\n                       bw = 2000,\n                       div = \"bw\",\n                       method = \"simple\",\n                       digits = 1,\n                       tol = 1,\n                       grid_shape = c(3, 3),\n                       max_depth = 8,\n                       agg = 5,\n                       sparse = TRUE,\n                       verbose = FALSE)\n\nlixels$density_500 <- densities_500 * 1000\nlixels$density_2000 <- densities_2000 * 1000\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmap_500 <- tm_shape(network) +\n  tm_lines(col = \"grey80\") +\ntm_shape(lixels %>% filter(density_500 > 0)) +\n  tm_lines(col = \"density_500\",\n           col.scale = tm_scale_intervals(style = \"quantile\",\n                                          values = \"viridis\"),\n           col.legend = tm_legend(title = \"NKDE, bw = 500 m\"),\n           lwd = 2)\n\nmap_2000 <- tm_shape(network) +\n  tm_lines(col = \"grey80\") +\ntm_shape(lixels %>% filter(density_2000 > 0)) +\n  tm_lines(col = \"density_2000\",\n           col.scale = tm_scale_intervals(style = \"quantile\",\n                                          values = \"viridis\"),\n           col.legend = tm_legend(title = \"NKDE, bw = 2 km\"),\n           lwd = 2)\n\ntmap_arrange(map_500, map_2000, ncol = 2)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-62-1.png){width=1344}\n:::\n:::\n\n\nThe summary statistics show how the range of density values changes with the bandwidth.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lixels$density_500)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. \n0.0000000 0.0000000 0.0000000 0.0009199 0.0000000 0.1394506 \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(lixels$density)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. \n0.000000 0.000000 0.000000 0.000577 0.000415 0.042352 \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(lixels$density_2000)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. \n0.000e+00 0.000e+00 6.496e-05 4.455e-04 4.375e-04 1.725e-02 \n```\n\n\n:::\n:::\n\n\n::: {.callout-note title=\"Interpretation\"}\n<!-- TODO: write after running. State whether the same corridors appear at all three bandwidths (compare with the 1 km map in Section 6.3), and how the maximum density changes. -->\n:::\n\n# 9. Integrated Findings and Discussion\n\n**What does the first-order analysis reveal?** Recorded accidents are highly uneven in space and time. NKDE shows that density is confined to a small number of specific roads, particularly corridors across southern Bangkok into Samut Prakan, into Pathum Thani and towards Samut Sakhon (Section 6.3); planar KDE shows the same corridors (Section 6.4). Temporally, counts are higher in the second half of 2022 (peaking in October) and spike during the New Year and Songkran campaign periods (Section 6.1), while the hotspot locations are stable through the year (Sections 6.5 and 6.6).\n\n**What does the second-order analysis reveal?** Against planar CSR, accidents are strongly clustered at all distances tested (Section 7.2). Against CSR on the road network, <!-- TODO: summarise the network K- and G-function result from Section 7.1 -->.\n\n**How do they complement each other?** The first-order results show that accidents are concentrated on a few roads, which explains much of the strong planar clustering. The network second-order test asks whether, along those roads, accidents are closer together than random placement on the network would produce. <!-- TODO: one sentence linking the network K result to the repeated locations in Section 5.9. -->\n\n**Are the findings consistent across analytical views?** The location of the main corridors is consistent across NKDE, planar KDE at 0.5-2 km bandwidths, and spatio-temporal KDE. The strength of clustering is not: it depends strongly on whether the null model is planar CSR or CSR on the network. <!-- TODO: add the NKDE bandwidth sensitivity result from Section 8. -->\n\n**What assumptions or limitations matter?** The most important are the observation process (only national road agencies' records), the absence of traffic-volume data, the restriction of the network K-function to Bangkok, and sensitivity to bandwidth; these are detailed in Section 11.\n\n**Are there alternative explanations?** Concentrations along corridors may reflect higher traffic volumes rather than higher risk per vehicle; network CSR assumes equal exposure on every road, which is unlikely. Repeated locations may partly reflect recording practices, such as locating accidents at fixed reference points, rather than true hotspots. Low intensity in inner Bangkok may reflect missing records from city-managed streets rather than safer roads.\n\n# 10. Public-safety Planning and Management Implications\n\n## Supported directly by the analysis\n\n**Prioritising road segments rather than areas.** NKDE shows that recorded accidents are concentrated on a small number of specific roads, particularly the corridors across southern Bangkok into Samut Prakan, the north–south corridor into Pathum Thani, and the south-western corridor towards Samut Sakhon. Road-safety audits, enforcement and engineering reviews can therefore be targeted at identified road segments rather than spread evenly across provinces.\n\n**Focusing on repeated locations.** Some accidents share exact locations (Section 5.9). These locations are natural candidates for site-level investigation, such as junction design, signage and lighting.\n\n**Timing interventions.** Accidents are more frequent in the second half of the year and during the New Year and Songkran periods. Enforcement and campaign resources can be scheduled to match these periods.\n\n**Monitoring emerging corridors.** The south-western corridor towards Samut Sakhon becomes more prominent from mid-year onwards (Section 6.6), suggesting it should be monitored over future years to see whether this pattern persists.\n\n**Emergency response.** Because accidents are concentrated along identifiable road segments, the locations of ambulance and rescue units can be evaluated against these segments, for example by checking response distances along the network.\n\n## Requiring additional information\n\n**Assessing risk rather than counts.** The analysis identifies where recorded accidents concentrate, not where roads are most dangerous. Traffic volume data would be needed to convert counts into accident rates per vehicle-kilometre before concluding that a road segment is high-risk.\n\n**Explaining causes.** The analysis does not show why accidents concentrate on these roads or at these times. Attributes such as presumed cause, vehicle type and road design, together with field inspections, would be needed before designing specific engineering or behavioural interventions.\n\n**Covering city streets.** All records come from national road agencies. Integrating data from the Bangkok Metropolitan Administration would be necessary before drawing conclusions about inner Bangkok, where low intensity may reflect missing records.\n\n**Evaluating interventions.** Multi-year data (for example, 2019–2022) would be needed to confirm whether the identified corridors and seasonal patterns are stable, and to evaluate whether past campaigns have had any effect.\n\n# 11. Limitations\n\n-   **Observation process.** All records come from national road agencies (Department of Highways 80.1%, Expressway Authority 13.1%, Department of Rural Roads 6.8%). Accidents on city-managed streets are likely missing, so patterns describe recorded accidents on these road types only.\n-   **No exposure data.** Without traffic volumes, concentrations cannot be interpreted as higher risk, and network CSR assumes equal exposure on all roads.\n-   **Location quality.** 189 records lacked coordinates, and some accidents share exact locations, possibly reflecting fixed reference points. These were kept, which inflates the planar G-function at distance zero.\n-   **Single year.** Only 2022 is analysed, so patterns may not be stable across years.\n-   **Bandwidth sensitivity.** Planar KDE and NKDE depend on bandwidth; results were compared at several bandwidths, but not all choices can be exhausted.\n-   **Limited simulations and extent.** The network K-function uses 50 simulations and covers Bangkok only, for computational reasons.\n-   **Temporal smoothing.** The day-of-year STKDE uses a 76-day temporal bandwidth, which smooths out short holiday peaks; the space–time K-function assumes constant intensity.\n-   **Network data.** The OSM road network is a 2026 extract, whereas accidents are from 2022, and only major road classes were included. Roads built after 2022 appear in the network without any accidents.\n-   **Study window.** BMR is defined by six provincial boundaries; a different definition of the metropolitan area could change edge effects and intensity estimates.\n\n# 12. References\n\n-   Asian Transport Observatory. (2025). *Thailand Road Safety Profile 2025*.\n-   Baddeley, A., Rubak, E., & Turner, R. (2015). *Spatial Point Patterns: Methodology and Applications with R*. Chapman and Hall/CRC.\n-   Davies, T. M., Marshall, J. C., & Hazelton, M. L. (2018). Tutorial on kernel estimation of continuous spatial and spatiotemporal relative risk. *Statistics in Medicine*, 37(7), 1191-1221.\n-   Gabriel, E., Rowlingson, B. S., & Diggle, P. J. (2013). stpp: An R package for plotting, simulating and analyzing spatio-temporal point patterns. *Journal of Statistical Software*, 53(2), 1-29.\n-   Gelb, J. (2021). spNetwork: A package for network kernel density estimation. *The R Journal*, 13(2), 102-116.\n-   Kam, T. S. *R for Geospatial Data Science and Analytics*, Chapter 7: Network Constrained Spatial Point Patterns Analysis. https://r4gdsa.netlify.app/chap07\n-   Okabe, A., & Sugihara, K. (2012). *Spatial Analysis along Networks: Statistical and Computational Methods*. Wiley.\n-   OpenStreetMap contributors. Thailand extract via Geofabrik, 21 September 2026.\n-   Runfola, D. et al. (2020). geoBoundaries: A global database of political administrative boundaries. *PLOS ONE*, 15(4), e0231866.\n-   Thaweewat R. Thailand Road Accident \\[2019-2022\\]. Kaggle.\n-   World Health Organization. (2023). *Global status report on road safety 2023*. Geneva: WHO.\n",
    "supporting": [
      "Take-home_Ex01_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}